[RU] Fixes for 11.2
northwood-studios/SCPSL-Translations pull request #1030
Opened 2022-04-15 14:43 UTC by REALMWTH

# **SCP:SL Translation PR Template**

## **Language Name**
Russian

## **State Type of change (New language, changed existing Etc.)**
Fixes of some inconsistencies between English and Russian translation.
Also contains rephrased versions of translation for easier understanding.

# **Checklist:**
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  *( Exception to this is when edits has __only__ been made in-browser. If this is the case, also* ***check this box*** *)*
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure my addition follows guidelines described in the [CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md) file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2022-05-04 12:42 UTC, GuyFawkes76 requested changes
Открыт для дискуссий.

2022-05-04 12:42 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Поддерживайте Micro H.I.D. в заряженном положении, удерживая правую клавишу мыши. При этом медленно расходуется его энергия.
Второе предложение плохо звучит в сочетании с первым.

2022-05-04 12:42 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Употребление содержимого бутылки SCP-207 не только увеличивает вашу скорость, но и частично восстановит ваше здоровье.
```suggestion
Употребление содержимого бутылки SCP-207 не только увеличит вашу скорость, но и частично восстановит ваше здоровье.
```

2022-05-04 12:42 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Бросив SCP-018 в коридоре, можно остановить ваших преследователей.
Спорно. Можно и так, но, мне кажется, можно лучше. Если ничего не придумается, сделаем так.

2022-05-04 12:42 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Ворота Тесла, за которыми наблюдает SCP-079, всегда будут активны.
Тут тоже не знаю насчёт ворот Тесла или Тесла-ворот.

2022-05-04 12:42 UTC, GuyFawkes76 commented on Translations/ru/SCP330.txt
> +Даёт длительную регенерацию здоровья и временный иммунитет к большинству побочных эффектов.
А они побочные?

2022-05-04 12:42 UTC, GuyFawkes76 commented on Translations/ru/Subtitles.txt
> +успешно сдержан Научным Сотрудником.
А надо ли здесь единственное число? Может, множественное?

2022-05-04 12:42 UTC, GuyFawkes76 commented on Translations/ru/Subtitles.txt
> +успешно сдержан Повстанцем Хаоса.
Тот же вопрос про единственное число.

2022-05-04 12:42 UTC, GuyFawkes76 commented on Translations/ru/Subtitles.txt
> +В пределах комплекса сохраняется серьёзная угроза безопасности -- соблюдайте осторожность.
Не знаю. "В пределах комплекса" звучит неестественно.

2022-05-04 12:42 UTC, GuyFawkes76 commented on Translations/ru/Subtitles.txt
> +Функционирование комплекса вернулось к штатному режиму.
В оригинале лучше, но не значит, что хорошо.

2022-05-04 12:42 UTC, GuyFawkes76 commented on Translations/ru/Summary.txt
> +Убитых Объектами SCP людей: [summary_scpfrags]
Зачем?

2022-08-04 14:11 UTC, Rnen commented
Closing this for now as requested changes has not been met. Reopen when changes has been made.

2022-08-04 14:11 UTC, closed without merging