[RU] Various translation improvements and fixes.
northwood-studios/SCPSL-Translations pull request #1054
Opened 2022-05-31 13:26 UTC by Jimm800

# **SCP:SL Translation PR Template**

## **Language Name**
(Russian)

## **State Type of change (New language, changed existing Etc.)**
(Сhanged existing translation)

# **Checklist:**
- [X] I have tested the translation changes ingame
- [X] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  *( Exception to this is when edits has __only__ been made in-browser. If this is the case, also* ***check this box*** *)*
- [X] I have made sure that I'm **not** submitting a duplicate translation 
- [X] I have made sure my addition follows guidelines described in the [CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md) file
- [X] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2022-06-09 22:32 UTC, bladuk commented on Translations/ru/manifest.json
> +    "Cauterizers Project"
You can't add yourself to the manifest file because your PR doesn't meet the requirements. [Details](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md#credits--author)

2022-06-10 11:36 UTC, Jimm800 commented on Translations/ru/manifest.json
> +    "Cauterizers Project"
Мне нужно это вырезать или это просто проигнорируют?

2022-06-10 13:04 UTC, Rnen submitted a review, later dismissed
As @bladuk pointed out, we have a minimum requirement for credits.
Please either comply with the requirements or revert the credits change. 
[CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md)

2022-08-06 19:36 UTC, bladuk commented
Perhaps the "manifest" tag should be removed? No changes will be applied to the manifest file with this PR.

2022-09-26 19:36 UTC, GuyFawkes76 requested changes

2022-09-26 19:36 UTC, GuyFawkes76 commented on Translations/ru/Abilities.txt
> +Старайся Не Плакать (Спокойствие):Опираясь на дверь, вы становитесь тише, успокаивая себя... или ожидая кого-нибудь, кто попробует пройти через неё.
Как мне кажется, исходный вариант больше подходит.

2022-09-26 19:36 UTC, GuyFawkes76 commented on Translations/ru/Class_Names.txt
> +Повстанец Хаоса — Подавитель
Спорно. Подавитель это скорее Oppressor или Suppressor.
Repressor может быть Угнетателем.

2022-09-26 19:46 UTC, GuyFawkes76 commented on Translations/ru/Abilities.txt
> +Старайся Не Плакать (Спокойствие):Опираясь на дверь, вы становитесь тише, успокаивая себя... или ожидая кого-нибудь, кто попробует пройти через неё.
```suggestion
Старайся Не Плакать (Утешение):Опираясь на дверь, вы становитесь тише, успокаивая себя... или ожидая кого-нибудь, кто попробует пройти через неё.
```

2022-09-26 19:46 UTC, GuyFawkes76 commented on Translations/ru/Class_Names.txt
> +Повстанец Хаоса — Подавитель
```suggestion
Повстанец Хаоса — Усмиритель
```

2022-09-26 19:48 UTC, GuyFawkes76 approved these changes

2022-09-26 19:52 UTC, merged