PL | Update 12.0
northwood-studios/SCPSL-Translations pull request #1111
Opened 2022-10-10 23:22 UTC by MultiverseUncle

# **SCP:SL Translation PR Template**

## **Language Name**
Polish

## **State Type of change (New language, changed existing Etc.)**
Added and updated files for 12.0. 
Oh, also redid my previous (already closed) merge request.

# **Checklist:**
- [X] I have tested the translation changes ingame
- [X] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  *( Exception to this is when edits has __only__ been made in-browser. If this is the case, also* ***check this box*** *)*
- [X] I have made sure that I'm **not** submitting a duplicate translation 
- [X] I have made sure my addition follows guidelines described in the [CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md) file
- [X] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2022-10-15 08:20 UTC, zabszk requested changes

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +ODNAWIANIE BLOKADY POMIESZCZENIA
Same as line 16.

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +ODNAWIANIE AKTYWACJI BRAMY TESLI
Same thing as previously.

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +$ZABLOKUJ POMIESZCZENIE$ jest dostępne - naciśnij $[key]$, aby zablokować wszystkie drzwi w pomieszczeniu.
These sound a little weird and not grammatically correct.

Maybe we should use forms like "GASZENIE ŚWIATEŁ jest dostępne"? Furthermore the translations are not consistent, two of them follow the format "feature - change" and some of them "feature change" (without the dash).

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/SCP939_HUD.txt
> +Naciśnij [key_attack] lub [key_jump] aby wyskoczyć.
```suggestion
Naciśnij [key_attack] lub [key_jump], aby wyskoczyć.
```

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/SCP939_HUD.txt
> +Zostałeś zabity przez SCP-939 i ukradł ci twój głos!
The second part of the sentence doesn't have any subject. Sentence "You have been killed by SCP-939 and stole your voice" is not correct. Furthermore "ci" in the second part is redundant.

We can either change "i" na ", który" or the entire sentence (eg. "SCP-939 cię zabił i ukradł twój głos").

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/SCP939_HUD.txt
> +Jeżeli nie chcesz aby twój głos był przez niego używany, możesz wyłączyć tę mechanikę.
```suggestion
Jeżeli nie chcesz, aby twój głos był przez niego używany, możesz wyłączyć tą funkcję.
```

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/SCP939_HUD.txt
> +SCP-939 używa mechaniki pozwalającej na nagrywanie kilku ostatnich sekund twojej rozmowy głosowej. Ona może być odtwarzana przez SCP-939, aby zwabić do siebie pozostałych graczy.\nNagrania są automat
```suggestion
SCP-939 używa mechaniki pozwalającej na nagrywanie kilku ostatnich sekund twojej rozmowy głosowej. Może być on odtwarzany przez SCP-939, aby zwabić do siebie pozostałych graczy.\nNagrania są automatycznie usuwane jeżeli opuścisz serwer, SCP-939 zginie lub gdy runda dobiegnie końca. Wyłączenie tej funkcji spowoduje usunięcie wszystkich nagrań twojego głosu.
```

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/Voicechat.txt
> +Odmów wszystko (wyłącz przechwytywanie mikrofonu)
```suggestion
Odmów wszystkiego (wyłącz przechwytywanie mikrofonu)
```

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/Voicechat.txt
> +Pozwól na używanie krótkich nagrań twojego głosu. Obejmuje to umiejętność SCP-939, "Z Wieloma Głosami", która może nagrywać i odtwarzać krótkie nagrania głosów zabitych graczy. Wszystkie nagrania zos
```suggestion
Pozwól na używanie krótkich nagrań twojego głosu. Obejmuje to umiejętność SCP-939 "Z Wieloma Głosami", która może nagrywać i odtwarzać krótkie nagrania głosów zabitych graczy. Wszystkie nagrania zostaną usunięte, gdy opuścisz serwer lub runda dobiegnie końca.
```

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/Voicechat.txt
> +Naciśnij "[key]" i wejdź w "Ustawienia" aby zmienić.
```suggestion
Naciśnij "[key]" i wejdź w "Ustawienia", aby zmienić.
```

2022-10-15 08:20 UTC, zabszk commented on Translations/pl/AttachmentEditors.txt
> +Personalizacja [Attachment]
Is the "[Attachment]" supposed to be untranslated?

2022-10-15 15:30 UTC, MultiverseUncle commented on Translations/pl/AttachmentEditors.txt
> +Personalizacja [Attachment]
The '[]' thingies suggest to me that [Attachment] is supposed to be a variable, similar to [key_attack], etc, so yeah, it should remain the same. Tho why it was made and where does it occur ingame is currently unknown (currently can't find it anywhere)

2022-10-16 09:16 UTC, zabszk submitted a review, later dismissed

2022-10-20 21:39 UTC, zabszk requested changes

2022-10-20 21:39 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +TRWA ODNAWIANIE GASZENIE ŚWIATEŁ CAŁEJ STREFY
```suggestion
TRWA ODNAWIANIE GASZENIA ŚWIATEŁ W CAŁEJ STREFIE
```

Typo and inconsistent with other strings.

2022-10-20 21:39 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +$GASZENIE ŚWIATEŁ CAŁEJ STREFY$ jest dostępne - przycisk znajduje się obok jej nazwy na $mapie placówki$.
```suggestion
$GASZENIE ŚWIATEŁ W CAŁEJ STREFIE$ jest dostępne - przycisk znajduje się obok jej nazwy na $mapie placówki$.
```

Consistency.

2022-10-20 21:39 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +DOSTĘPNA KAMERA ONLINE
The translation doesn't really make any sense, offline camera can't be really available in this case.

Additionally I'm not sure whether the original string means that the CCTV camera is available or that the feed from the CCTV camera is now live on the screen.

2022-10-21 15:51 UTC, MultiverseUncle commented on Translations/pl/SCP079_HUD.txt
> +DOSTĘPNA KAMERA ONLINE
Original string means that the feed from the camera is now live on the screen (aka 079's screen).
Btw, the same translated string was also used in old 079, but I guess I will just remove the "available" part from it.

2022-10-21 16:07 UTC, zabszk approved these changes

2022-10-22 20:25 UTC, merged