PL | "New F1 descriptions" Update
northwood-studios/SCPSL-Translations pull request #1232
Opened 2022-11-29 17:05 UTC by MultiverseUncle

# **SCP:SL Translation PR Template**

## **Language Name**
Polish

## **State Type of change (New language, changed existing Etc.)**
- Added and removed 3 files.
- Updated existing SCP HUD files.
**Note:**
Bio and human abilities were mostly borrowed from the previous files, however they were adjusted and updated to match the new text.

# **Checklist:**
- [X] I have tested the translation changes ingame
- [X] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  *( Exception to this is when edits has __only__ been made in-browser. If this is the case, also* ***check this box*** *)*
- [X] I have made sure that I'm **not** submitting a duplicate translation 
- [X] I have made sure my addition follows guidelines described in the [CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md) file
- [X] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2022-12-02 23:32 UTC, zabszk requested changes
That's the first batch of requested changes.

2022-12-02 23:32 UTC, zabszk commented on Translations/pl/HumanAbilities.txt
> +Karta dostępu:Posiadasz kartę dostępu, nie jest ona najlepsza, ale lepiej jej nie zgub.
```suggestion
Karta dostępu:Posiadasz kartę dostępu. Nie jest ona najlepsza, ale lepiej jej nie zgub.
```

2022-12-02 23:32 UTC, zabszk commented on Translations/pl/HumanAbilities.txt
> +Ekwipunek:Otwórz ekwipunek i wybierz przedmiot lewym przyciskiem myszy lub upuść, używając prawego przycisku myszy.
```suggestion
Ekwipunek:Otwórz ekwipunek i wybierz przedmiot, używając lewego przycisku myszy. Możesz też upuścić przedmiot, używając prawego przycisku myszy.
```

2022-12-02 23:32 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +SCP-079 nie ma bezpośrednich możliwości walki lub ruchu. Zamiast tego, widzisz świat przez kamery znajdujące się w każdym pomieszczeniu. Każda dostępna umiejętność jest wyświetlana w prawym górnym ro
```suggestion
SCP-079 nie ma bezpośrednich możliwości walki lub ruchu. Zamiast tego widzisz świat przez kamery znajdujące się w każdym pomieszczeniu. Wszystkie dostępne umiejętności są wyświetlane w prawym górnym rogu twojego ekranu.
```

2022-12-02 23:32 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +Praktycznie niezniszczalny:Trzy generatory znajdują się w Strefie Wyższego Nadzoru. Gdy wszystkie zostaną aktywowane, będziesz mógł zostać zabezpieczony w swojej celi przechowawczej. Każdy generator
```suggestion
Praktycznie niezniszczalny:Trzy generatory znajdują się w Strefie Wyższego Nadzoru. Gdy zostaną aktywowane, będziesz mógł zostać zabezpieczony w swojej celi przechowawczej. Każdy generator ma sekwencję odliczania, która może zostać przerwana poprzez kliknięcie przycisku "ANULUJ" na generatorze.
```

2022-12-02 23:32 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +Nieograniczony dostęp:Możesz kontrolować wieloma systemami w placówce, pomagając innym podmiotom SCP. Prawy górny róg twojego ekranu wyświetla dostępne umiejętności. Te umiejętności zużywają energię,
```suggestion
Nieograniczony dostęp:Możesz kontrolować wiele systemów w placówce, pomagając innym podmiotom SCP. Prawy górny róg twojego ekranu wyświetla dostępne umiejętności. Każda umiejętność zużywa energię, która z czasem się regeneruje.
```

2022-12-02 23:32 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +Obserwacja:Będąc wszędzie i nigdzie posiadasz unikalną perspektywę na całą placówkę. Możesz zaznaczać lokacje, ludzi oraz obiekty zainteresowań, pomagając członkom drużyny w rzeźni.
```suggestion
Obserwacja:Będąc wszędzie i nigdzie posiadasz unikatową perspektywę całej placówki. Możesz zaznaczać lokacje, ludzi oraz obiekty zainteresowań, pomagając członkom drużyny w rzeźni.
```

2022-12-11 15:10 UTC, zabszk requested changes

2022-12-11 15:10 UTC, zabszk commented on Translations/pl/SCP096_HUD.txt
> +Przytrzymaj [key] aby wpaść w szał.
```suggestion
Przytrzymaj [key], aby wpaść w szał.
```

2022-12-11 15:10 UTC, zabszk commented on Translations/pl/SCP096_HUD.txt
> +Przytrzymaj [key] aby wyjść z szału.
```suggestion
Przytrzymaj [key], aby wyjść z szału.
```

2022-12-11 15:10 UTC, zabszk commented on Translations/pl/SCP096_HUD.txt
> +SCP-096 jest spokojny, lecz wpada w szał gdy ktoś go ujrzy lub zrani. Szał wzmacnia go wieloma umiejętnościami, pomagając SCP-096 ścigać winnych zanim minie.
```suggestion
SCP-096 jest spokojny, lecz wpada w szał, gdy ktoś go ujrzy lub zrani. Szał wzmacnia go wieloma umiejętnościami, pomagając SCP-096 ścigać winnych zanim minie.
```

2022-12-11 15:10 UTC, zabszk commented on Translations/pl/SCP096_HUD.txt
> +Spróbuj nie płakać:Jest ciężko... lecz oparcie się o coś może ci pomóc uspokoić się, by się schować... lub zaczekać aż ktoś się do ciebie zbliży.
```suggestion
Spróbuj nie płakać:Jest ciężko... lecz oparcie się o coś może ci pomóc uspokoić się, by się schować... lub zaczekać, aż ktoś się do ciebie zbliży.
```

2022-12-11 15:55 UTC, MichalPetryka requested changes

2022-12-11 15:55 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Amnezyjna obłoka:Wypełnij powietrze niebezpiecznym neurochemicznym gazem, którego zasięg będzie zależał od długości wypuszczania go. Ludzie, którzy wdechną ten gaz nie spostrzegą SCP-939 oraz nie będ
`Amnezyjna obłoka` isn't even valid polish, use `Obłok zapomnienia` or `Amnezyjny obłok` instead, the first one is slightly different but sounds better.

2022-12-11 20:52 UTC, zabszk requested changes

2022-12-11 20:52 UTC, zabszk commented on Translations/pl/HumanAbilities.txt
> +Bieg:Zwiększa twoją prędkość ruchu, lecz poruszasz się wówczas głośniej.
```suggestion
Bieg:Poruszasz się szybciej, lecz głośniej.
```

2022-12-11 20:52 UTC, zabszk commented on Translations/pl/HumanAbilities.txt
> +Skradanie:Twoje ruchy są cichsze, lecz wolniejsze.
```suggestion
Skradanie:Poruszasz się ciszej, lecz wolniej.
```

2022-12-11 20:52 UTC, zabszk commented on Translations/pl/SCP049_HUD.txt
> +Atak serca:Wyciągasz przed siebie dłoń aby dotknąć serc ofiarom zarazy, zatrzymując im funkcje życiowe i dając tobie szansę na podanie lekarstwa.
```suggestion
Atak serca:Wyciągasz przed siebie dłoń, aby dotknąć serc ofiarom zarazy, zatrzymując im funkcje życiowe i dając sobie szansę na podanie lekarstwa.
```

2022-12-11 20:52 UTC, zabszk commented on Translations/pl/SCP049_HUD.txt
> +Świetne wyczucie doktora:Przenosisz swoje skupienie na skażoną duszę. Poruszasz się szybciej, zdeterminowany aby pozbyć się zarazy. Jesteś w stanie wskazać jej odległość od ciebie dzięki znanemu ci a
```suggestion
Świetne wyczucie doktora:Przenosisz swoje skupienie na skażoną duszę. Poruszasz się szybciej, zdeterminowany, aby pozbyć się zarazy. Jesteś w stanie wskazać jej odległość od ciebie dzięki znanemu ci aromatu.
```

2022-12-11 20:52 UTC, zabszk commented on Translations/pl/SCP049_HUD.txt
> +Nie marnuje, nie brakuje:Twoje intuicje medyczne nie są bez potrzeby na efektywność. Możesz wskrzeszać wyleczonych ponownie i ponownie. To nie codzienność aby martwi powstali dwa razy.
```suggestion
Nie marnuje, nie brakuje:Twoje intuicje medyczne nie są bez potrzeby na efektywność. Możesz wskrzeszać wyleczonych ponownie i ponownie. To nie codzienność, aby martwi powstali dwa razy.
```

2022-12-11 20:52 UTC, zabszk commented on Translations/pl/SCP049_HUD.txt
> +Żarłoczność:Lekarstwowi nie brakuje zalet. Jesteś w stanie zregenerować swoje ciało, używając pobliskich ci zwłok. Nie ma jednak dzielenia się nimi, także pamiętaj aby być pierwszym na uczcie.
```suggestion
Żarłoczność:Lekarstwu nie brakuje zalet. Jesteś w stanie zregenerować swoje ciało, używając pobliskich ci zwłok. Nie ma jednak dzielenia się nimi. Pamiętaj, aby być pierwszym na uczcie.
```

2022-12-11 20:52 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +Nieograniczony dostęp:Możesz kontrolować wiele systemów w placówce, pomagając innym podmiotom SCP. Prawy górny róg twojego ekranu wyświetla dostępne umiejętności. Każda umiejętność zużywa energię, kt
```suggestion
Nieograniczony dostęp:Możesz kontrolować wiele systemów w placówce, pomagając innym podmiotom SCP. W prawym górnym rogu twojego ekranu wyświetlane są dostępne umiejętności. Każda z nich zużywa energię, która z czasem się regeneruje.
```

2022-12-11 20:52 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +Uczenie głębokie:Pomaganie podmiotom SCP jest wynagradzane w postaci doświadczenia, potrzebnego do uzyskania nowego poziomu dostępu. Każdy kolejny poziom zapewnia więcej energii oraz nowe umiejętnośc
```suggestion
Uczenie głębokie:Pomaganie podmiotom SCP jest wynagradzane w postaci doświadczenia, potrzebnego do uzyskania następnego poziomu dostępu. Każdy kolejny poziom zapewnia więcej energii oraz nowe umiejętności.
```

2022-12-11 20:52 UTC, zabszk commented on Translations/pl/SCP106_HUD.txt
> +Śledzenie:Zanurzasz się pod ziemię. Jesteś wtedy niewidoczny oraz szybko się przemieszczasz, regenerując i przygotowując na zaatakowanie ofiary. Ta umiejętność zużywa wigor, który powoli się regeneru
```suggestion
Śledzenie:Zanurzasz się pod ziemię. Jesteś wtedy niewidoczny oraz szybko się przemieszczasz. Regenerujesz się i przygotowujesz do zaatakowania ofiary. Ta umiejętność zużywa wigor, który powoli się regeneruje, gdy nie jest ona używana.
```

2022-12-11 20:52 UTC, zabszk commented on Translations/pl/SCP173_HUD.txt
> +Karkołomna prędkość:Twoja prędkość jest znacznie zwiększona, natomiast nie jesteś w stanie nikogo zaatakować. Ta umiejętność może być anulowana przez ciebie lub po byciu zauważonym. Pchaj naprzód lub
```suggestion
Karkołomna prędkość:Twoja prędkość jest znacznie zwiększona, ale nie jesteś w stanie nikogo zaatakować. Możesz wyłączyć tą umiejętność w każdej chwili. Jest ona także automatycznie wyłączana, gdy zostaniesz zauważony. Szarżuj lub uciekaj w mgnieniu oka.
```

2022-12-11 21:04 UTC, zabszk requested changes

2022-12-11 21:04 UTC, zabszk commented on Translations/pl/SCP939_HUD.txt
> +Amnezyjny obłok:Wypełnij powietrze niebezpiecznym neurochemicznym gazem, którego zasięg będzie zależał od długości wypuszczania go. Ludzie, którzy wdechną ten gaz nie spostrzegą SCP-939 oraz nie będą
```suggestion
Amnezyjny obłok:Wypełnij powietrze niebezpiecznym neurochemicznym gazem, którego zasięg będzie zależał od długości wypuszczania go. Ludzie, którzy wdechną ten gaz, nie spostrzegą SCP-939 oraz nie będą mogli wykonać pewnych czynności. Natomiast atakowanie ich lub bycie atakowanym chwilowo cię ujawni.
```

2022-12-11 21:04 UTC, zabszk commented on Translations/pl/SCP939_HUD.txt
> +Koncentracja:Poświęcając całą energię na swoich zmysłach, możesz widzieć ofiary z dalekiej odległości oraz kim dokładnie są.
```suggestion
Koncentracja:Poświęcając całą energię na swoich zmysłach, możesz widzieć ofiary z dalekiej odległości. Możesz ustalić kim one są analizują ich zachowanie.
```

2022-12-11 21:04 UTC, zabszk commented on Translations/pl/SCP939_HUD.txt
> +Imituj wszystkie dźwięki z twojego miejsca
```suggestion
Emituj wszystkie dźwięki z twojego obecnego położenia
```

2022-12-11 21:16 UTC, zabszk approved these changes

2022-12-12 02:38 UTC, MichalPetryka requested changes

2022-12-12 02:38 UTC, MichalPetryka commented on Translations/pl/SCP049_HUD.txt
> +Nie marnuje, nie brakuje:Twoje intuicje medyczne nie są bez potrzeby na efektywność. Możesz wskrzeszać wyleczonych ponownie i ponownie. To nie codzienność, aby martwi powstali dwa razy.
Translating it literally makes no sense.

2022-12-12 07:15 UTC, zabszk requested changes

2022-12-12 07:15 UTC, zabszk commented on Translations/pl/SCP173_HUD.txt
> +Wzmocniony beton:Twoje betonowe ciało staje czoła przeciw wandalizmowi. Bronie niskiej penetracji zadają twojemu zdrowiu o wiele mniej obrażeń. Mogą podziwiać, lecz nigdy dotykać.
```suggestion
Zbrojony beton:Twoje betonowe ciało staje czoła przeciw wandalizmowi. Bronie niskiej penetracji zadają twojemu zdrowiu o wiele mniej obrażeń. Mogą podziwiać, lecz nigdy dotykać.
```

2022-12-12 10:29 UTC, MultiverseUncle commented on Translations/pl/SCP049_HUD.txt
> +Nie marnuje, nie brakuje:Twoje intuicje medyczne nie są bez potrzeby na efektywność. Możesz wskrzeszać wyleczonych ponownie i ponownie. To nie codzienność, aby martwi powstali dwa razy.
Elaborate

2022-12-12 10:47 UTC, zabszk commented on Translations/pl/SCP049_HUD.txt
> +Nie marnuje, nie brakuje:Twoje intuicje medyczne nie są bez potrzeby na efektywność. Możesz wskrzeszać wyleczonych ponownie i ponownie. To nie codzienność, aby martwi powstali dwa razy.
@MichalPetryka meant that `Nie marnuje, nie brakuje` is translated literally/directly. The original string is `Waste Not, Want Not` and it's a proverb/idiom, so it shouldn't be translated literally.

2022-12-12 18:08 UTC, MultiverseUncle commented on Translations/pl/SCP049_HUD.txt
> +Nie marnuje, nie brakuje:Twoje intuicje medyczne nie są bez potrzeby na efektywność. Możesz wskrzeszać wyleczonych ponownie i ponownie. To nie codzienność, aby martwi powstali dwa razy.
Updated

2022-12-12 19:56 UTC, zabszk submitted a review, later dismissed

2022-12-14 22:16 UTC, MichalPetryka requested changes

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP049_HUD.txt
> +Lobotomizowana żądza krwi:Twój umysł został usilnie usunięty, pozostawiając cię tylko z przemocą. Znajdujesz siebie ścigających ludzi coraz szybciej i szybciej, aż do nich dotrzesz ...
```suggestion
Lobotomiczna żądza krwi:Twój umysł został przymusowo usunięty, zostawiając ci tylko przemoc. Znajdujesz ścigających ciebie ludzi coraz szybciej i w końcu do nich dotrzesz ...
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP049_HUD.txt
> +Żarłoczność:Lekarstwu nie brakuje zalet. Jesteś w stanie zregenerować swoje ciało, używając pobliskich ci zwłok. Nie ma jednak dzielenia się nimi. Pamiętaj, aby być pierwszym na uczcie.
```suggestion
Zachłanność:Lekarstwo nie jest bez zalet. Jesteś w stanie regenerować swoje ciało, używając pobliskich zwłok. Nie ma jednak dzielenia się nimi. Pamiętaj aby być pierwszym na uczcie.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP079_HUD.txt
> +SCP-079 nie ma bezpośrednich możliwości walki lub ruchu. Zamiast tego widzisz świat przez kamery znajdujące się w każdym pomieszczeniu. Wszystkie dostępne umiejętności są wyświetlane w prawym górnym
```suggestion
SCP-079 nie ma możliwości bezpośredniej walki lub ruchu. Zamiast tego widzisz świat przez kamery znajdujące się w każdym pomieszczeniu. Wszystkie dostępne umiejętności są wyświetlane w prawym górnym rogu twojego ekranu.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP079_HUD.txt
> +Obserwacja:Będąc wszędzie i nigdzie posiadasz unikatową perspektywę całej placówki. Możesz zaznaczać lokacje, ludzi oraz obiekty zainteresowań, pomagając członkom drużyny w rzeźni.
```suggestion
Obserwacja:Będąc wszędzie i zarazem nigdzie posiadasz unikatową perspektywę całej placówki. Możesz zaznaczać lokacje, ludzi oraz obiekty zainteresowań, pomagając członkom drużyny w rzeźni.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP096_HUD.txt
> +Gdy spokojny
```suggestion
Poza szałem
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP096_HUD.txt
> +SCP-096 jest spokojny, lecz wpada w szał, gdy ktoś go ujrzy lub zrani. Szał wzmacnia go wieloma umiejętnościami, pomagając SCP-096 ścigać winnych zanim minie.
```suggestion
SCP-096 jest spokojny, lecz wpada w szał, gdy ktoś go ujrzy lub zrani. Szał wzmacnia go wieloma umiejętnościami, pomagając SCP-096 ścigać winnych w trakcie trwania.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP106_HUD.txt
> +Atlas łowcy:Przenieś się do pobliskiego pomieszczenia, kosztem dużego zużycia wigoru. Ten ruch jest dla ciebie instynktowny, po długim grasowaniu w korytarzach placówki.
```suggestion
Atlas łowcy:Przenieś się do pobliskiego pomieszczenia, kosztem dużego zużycia wigoru. Ten ruch jest dla ciebie instynktowny dzięki długiemu grasowaniu po korytarzach placówki.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP173_HUD.txt
> +Mrugnięcie:Gdy oko zaświeci się na czerwono, przytrzymaj i przenieś wskaźnik do określonego miejsca. Puść, aby się tam teleportować i zabić będącą tam ofiarę. Niech zapłacą za mrugnięcie w twojej obe
```suggestion
Mrugnięcie:Gdy oko zaświeci się na czerwono, przytrzymaj i przenieś wskaźnik do określonego miejsca. Puść, aby się tam teleportować i zabić będącą tam ofiarę. Niech zapłacą za chwilę nieuwagi.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP173_HUD.txt
> +Zbrojony beton:Twoje betonowe ciało staje czoła przeciw wandalizmowi. Bronie niskiej penetracji zadają twojemu zdrowiu o wiele mniej obrażeń. Mogą podziwiać, lecz nigdy dotykać.
```suggestion
Zbrojony beton:Twoje betonowe ciało stawia czoła wandalizmowi. Bronie niskiej penetracji zadają tobie o wiele mniej obrażeń. Mogą podziwiać, lecz nie dotykać.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP173_HUD.txt
> +Furia:Gdy niewidoczny, możesz stworzyć kałużę spowalniającą ludzi. Brak wielbicieli doprowadza cię do furii, także to powinno przyciągnąć ich uwagę.
```suggestion
Furia:Poza obserwacją możesz stworzyć kałużę spowalniającą ludzi. Brak wielbicieli doprowadza cię do furii, zaś to powinno przykuć ich uwagę.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Szpony:Naciśnij, aby machnąć szeroko swoimi szponami, ciąć ciała i kości swoim ofiarom. Podczas koncentracji główny atak pozwoli ci wyskoczyć na znalezioną zdobycz.
```suggestion
Szpony:Naciśnij, aby machnąć szeroko swoimi szponami, ciąć ciało i łamać kości swoim ofiarom. Podczas koncentracji główny atak pozwoli ci rzucić się na znalezioną zdobycz.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Amnezyjny obłok:Wypełnij powietrze niebezpiecznym neurochemicznym gazem, którego zasięg będzie zależał od długości wypuszczania go. Ludzie, którzy wdechną ten gaz, nie spostrzegą SCP-939 oraz nie będ
```suggestion
Amnezyjny obłok:Wypełnij powietrze niebezpiecznym neurochemicznym gazem, którego zasięg będzie zależał od długości wypuszczania go. Ludzie, którzy wdechną ten gaz, nie spostrzegą SCP-939 oraz nie będą mogli wykonywać pewnych czynności. Natomiast atakowanie ich lub bycie atakowanym chwilowo cię ujawni.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +O wielu głosach:Po zabiciu ofiary masz szansę na otrzymanie jej ostatnich słów, pozwalając na użycie ich w celu zmylenia innych. SCP-939 może również imitować niektóre dźwięki, w tym kroki ludzkie.
```suggestion
O wielu głosach:Po zabiciu ofiary masz szansę na otrzymanie jej ostatnich słów, pozwalając na użycie ich w celu zmylenia innych. SCP-939 może również udawać niektóre dźwięki, na przykład kroki ludzi.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Ultraczułość:SCP-939 jest w stanie wyczuć pobliskie źródła ciepła w postaci normalnej wizji małego zasięgu. Natomiast dalej musisz polegać na dźwiękach, aby znaleźć swoją zdobycz. Głośniejsze dźwięki
```suggestion
Ultraczułość:SCP-939 jest w stanie wyczuć pobliskie źródła ciepła w postaci normalnej wizji małego zasięgu. Dalej natomiast musisz polegać na dźwiękach, aby znaleźć swoją zdobycz. Głośniejsze dźwięki są widoczne z większej odległości. Wytrzymałość wpływa na zasięg twojej wizji.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Usunięto źródło dźwięku. Jesteś poza zasięgiem.
```suggestion
Usunięto źródło dźwięku. Opuszczono zasięg.
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Emituj wszystkie dźwięki z twojego obecnego położenia
```suggestion
Wydawaj wszystkie dźwięki z twojego obecnego położenia
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Wróć
Would `Powrót` be better here maybe?

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Ukradzione głosy
```suggestion
Skradzione głosy
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Imituj głosy swoich ofiar
```suggestion
Udawaj głosy swoich ofiar
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Imituj różne dźwięki aby zmylić ludzi
```suggestion
Udawaj różne dźwięki aby zmylić ofiary
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Imitacja
```suggestion
Udawanie
```

2022-12-14 22:16 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Następne menu
Is `menu` needed here?

2022-12-15 20:03 UTC, zabszk approved these changes

2022-12-15 20:53 UTC, MichalPetryka approved these changes

2022-12-15 20:54 UTC, merged