[PL] Breach Scanner & Mimicry, Normalizer, MTF -> MFO and other minor changes
northwood-studios/SCPSL-Translations pull request #1298
Opened 2023-03-28 00:07 UTC by TTypiarz

# **SCP:SL Translation PR Template**

## **Language Name**
Polish

## **State Type of change (New language, changed existing Etc.)**
- Ran `EncodingNormalizer.exe` on all files
- Added new Badges (https://github.com/northwood-studios/SCPSL-Translations/pull/1294)
- Updated 939 and 079 HUD (https://github.com/northwood-studios/SCPSL-Translations/pull/1288)
- Updated candy descriptions
- Updated LCZ decontamination subtitles (excluding the first and the last one)
- **Changed `MTF` to `MFO`**
> **Note**
> iirc. In older versions of the game MTF was translated to MFO. I'm not sure why it was changed to MTF.

# **Checklist:**
- [ ] I have tested the translation changes ingame
- [X] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  *( Exception to this is when edits has __only__ been made in-browser. If this is the case, also* ***check this box*** *)*
- [X] I have made sure that I'm **not** submitting a duplicate translation 
- [X] I have made sure my addition follows guidelines described in the [CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md) file
- [X] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2023-04-01 19:57 UTC, zabszk requested changes

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/LoadingHints.txt
> +Micro H.I.D potrzebuje pięciu sekund aby w pełni przygotować się do wystrzału.
```suggestion
Micro H.I.D potrzebuje pięciu sekund, aby w pełni przygotować się do wystrzału.
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/LoadingHints.txt
> +SCP-2176 może zostać użyty do zablokowania oraz odblokowywania drzwi w danym pomieszczeniu, również odblokowywuje drzwi zablokowane przez SCP-079.
```suggestion
SCP-2176 może zostać użyty do zablokowania oraz odblokowywania drzwi w danym pomieszczeniu. Odblokowywuje również drzwi zablokowane przez SCP-079.
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/LoadingHints.txt
> +SCP-244 spowalnia prędkość z jaką można podnosić przedmioty i powstrzymuje SCP przed regeneracją swoich tarcz.
```suggestion
SCP-244 zmniejsza prędkość, z jaką można podnosić przedmioty i powstrzymuje SCP przed regeneracją swoich tarcz.
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/LoadingHints.txt
> +Za pomocą SCP-914 możesz wytworzyć wiele unikalnych przedmiotów, których nie można zdobyć nigdzie indziej. Zachęcamy do eksperymentowania!
```suggestion
Za pomocą SCP-914 możesz wytworzyć wiele unikatowych przedmiotów, których nie można zdobyć nigdzie indziej. Zachęcamy do eksperymentowania!
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/LoadingHints.txt
> +SCP-079 odblokowuje skaner wyłomów od czwartego poziomu. Jeżeli wykryje on w pomieszczeniu ukrywającego się człowieka, odpali się alarm.
```suggestion
SCP-079 odblokowuje skaner wyłomów od czwartego poziomu. Jeżeli wykryje on w pomieszczeniu ukrywającego się człowieka, aktywuje się alarm.
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/LoadingHints.txt
> +SCP-106 jest w stanie dostrzec osoby na niewielki zasięg, gdy używa swojej umiejętności prześladowania.
```suggestion
SCP-106 jest w stanie dostrzec osoby w pobliżu, gdy używa swojej umiejętności prześladowania.
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/LoadingHints.txt
> +SCP-106 może otworzyć mapę pobliskich pomieszczeń, do których może się teleportować (domyślnie pod "TAB")
```suggestion
SCP-106 może otworzyć mapę pobliskich pomieszczeń, do których może się teleportować (domyślnie pod "TAB").
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +$SKANER WYŁOMÓW$ jest dostępny — wybierz drużyny/strefy na $mapie Placówki$ aby cyklicznie skanować w poszukiwaniu pozostałych ocalałych.
```suggestion
$SKANER WYŁOMÓW$ jest dostępny — wybierz drużyny/strefy na $mapie Placówki$, aby cyklicznie skanować w poszukiwaniu pozostałych ocalałych.
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +ZAWIESZONO REGENERACJE ENERGII
```suggestion
ZAWIESZONO REGENERACJĘ ENERGII
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +ZMNIEJSZONO REGENERACJE ENERGII ([precentage])
```suggestion
ZMNIEJSZONO REGENERACJĘ ENERGII ([precentage])
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +Skaner wyłomów wykrywa pozostałe cele, które przebywają przez dłuższy czas w tym samym obszarze.
```suggestion
Skaner wyłomów wykrywa pozostałe cele, które przebywają przez dłuższy czas na tym samym obszarze.
```

2023-04-01 19:57 UTC, zabszk commented on Translations/pl/SCP939_HUD.txt
> +Skrót  [key]
```suggestion
Skrót [key]
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +Micro H.I.D potrzebuje pięciu sekund, aby w pełni przygotować się do wystrzału.
```suggestion
Micro H.I.D potrzebuje pięciu sekund, aby przygotować się do wystrzału.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +Osoba, która jest pod wpływem SCP-268 jest niewidzialna dla każdego, lecz SCP-079 oraz SCP-939 dalej mogą ją zauważyć.
```suggestion
Osoba pod wpływem SCP-268 jest niewidzialna dla każdego, lecz SCP-079 oraz SCP-939 dalej mogą ją zauważyć.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-330 może dać sześć unikalnych cukierków, z czego każdy ma swój własny efekt. Nie bierz więcej niż dwa!
```suggestion
SCP-330 zawiera sześć rodzajów cukierków, z czego każdy ma swój własny efekt. Nie bierz więcej niż dwa!
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-1853 pozwala na szybsze przeładowanie broni i zmniejsza odrzut broni podczas strzelania.
```suggestion
SCP-1853 pozwala na szybsze przeładowanie broni i zmniejsza odrzut podczas strzelania.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-2176 może zostać użyty do zablokowania oraz odblokowywania drzwi w danym pomieszczeniu. Odblokowywuje również drzwi zablokowane przez SCP-079.
```suggestion
SCP-2176 może zostać użyty do blokowania oraz odblokowywania drzwi w danym pomieszczeniu. Działa również na drzwi pod kontrolą SCP-079.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-2176 może zostać użyty do oszołomienia SCP-079, jeśli zostanie użyty w pomieszczeniu, w którym on się znajduje.
```suggestion
SCP-2176 może zostać użyty do oszołomienia SCP-079, jeśli zostanie użyty w pomieszczeniu które on obserwuje.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-244 zmniejsza prędkość, z jaką można podnosić przedmioty i powstrzymuje SCP przed regeneracją swoich tarcz.
```suggestion
SCP-244 zmniejsza prędkość, z jaką można podnosić przedmioty i powstrzymuje regenerację tarcz innych SCP.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-079 może zablokować drzwi, gasić światła oraz aktywować wyładowania elektryczne na bramach tesli.
```suggestion
SCP-079 może blokować drzwi, gasić światła oraz aktywować wyładowania elektryczne na bramach tesli.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-079 może zmieniać przybliżenie swoich kamer za pomocą kółka myszy.
```suggestion
SCP-079 może zmieniać przybliżenie kamer za pomocą kółka myszy.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-079 odblokowuje skaner wyłomów od czwartego poziomu. Jeżeli wykryje on w pomieszczeniu ukrywającego się człowieka, aktywuje się alarm.
```suggestion
SCP-079 odblokowuje wykrywacz wyłomów od czwartego poziomu. Jeżeli wykryje on w pomieszczeniu ukrywającego się człowieka, aktywuje się alarm.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +Kamera używana przez SCP-079 zaświeci się na niebiesko. Miej się na baczności! Nigdy nie wiadomo, kiedy będzie obserwować.
```suggestion
Kamera używana przez SCP-079 świeci się na niebiesko. Miej się na baczności - nigdy nie wiadomo kto cię obserwuje...
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-106 jest najbardziej wrażliwy na ataki podczas zaraz po wynurzeniu się z ziemi.
```suggestion
SCP-106 jest najbardziej wrażliwy na ataki podczas wynurzenia się z ziemi.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-096 jest najbardziej wrażliwy na ataki, gdy zaczyna się uspokajać.
```suggestion
SCP-096 jest najbardziej wrażliwy na ataki, gdy uspokaja się.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-096 potrafi szarżować, gdy jest wściekły - wyłamuje drzwi i zabija cele.
```suggestion
SCP-096 gdy wściekły, potrafi szarżować - wyłamuje wtedy drzwi i zabija cele.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +Użycie adrenaliny neutralizuje działanie obłoku amnezyjnego SCP-939.
```suggestion
Użycie adrenaliny neutralizuje działanie amnezyjnego obłoku SCP-939.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-049 może natychmiast zabić każdego człowieka będącego już pod wpływem efektu akcji zatrzymania serca.
```suggestion
SCP-049 może natychmiast zabić każdego człowieka będącego już pod wpływem efektu zatrzymania akcji serca.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +Zatrzymanie akcji serca gwałtownie pozbawia twoje zdrowie. Będziesz potrzebował wielu środków medycznych, jeżeli chcesz go przetrwać.
```suggestion
Zatrzymanie akcji serca gwałtownie pozbawia cię zdrowia. Będziesz potrzebował wiele środków medycznych, jeżeli chcesz je przetrwać.
```

2023-04-01 21:13 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +SCP-049 może dać drobną tarczę dla podmiotów SCP-049-2, które znajdują się w pobliżu.
```suggestion
SCP-049 może dać słabą tarczę dla podmiotów SCP-049-2, które znajdują się w pobliżu.
```

2023-04-02 12:49 UTC, zabszk commented on Translations/pl/SCP079_HUD.txt
> +ZMNIEJSZONO REGENERACJĘ ENERGII ([precentage])
I think it should be without `(` and `)` in this case.

2023-04-02 22:30 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Zaznacz ulubione. Nagrania oznaczone jako ulubione przypisywane są do skrótów.
```suggestion
Zaznacz ulubione. Nagrania oznaczone jako ulubione zostaną przypisane do skrótów.
```

2023-04-02 22:30 UTC, MichalPetryka commented on Translations/pl/LoadingHints.txt
> +Ochroniarze są kiepscy w pojedynkę, ale są mocniejsi w grupie. W grupie siła!
```suggestion
Ochroniarze są kiepscy w pojedynkę, jednak razem są mocniejsi. W grupie siła!
```

2023-04-02 22:30 UTC, MichalPetryka commented on Translations/pl/SCP939_HUD.txt
> +Odtwórz głos (każdy go usłyszy)
```suggestion
Odtwórz głos (usłyszy go każdy)
```

2023-04-02 22:30 UTC, MichalPetryka commented on Translations/pl/SCP330.txt
> +Silny zapach wiśni wypełnia pomieszczenie. Jest troszkę <i>za mocny</i>.
```suggestion
Silny zapach wiśni wypełnia pomieszczenie. Jest lekko <i>przytłaczający</i>.
```

2023-04-03 01:00 UTC, MichalPetryka approved these changes

2023-04-03 12:55 UTC, zabszk approved these changes

2023-04-03 12:57 UTC, merged