Added Language
northwood-studios/SCPSL-Translations pull request #603
Opened 2020-08-25 14:11 UTC by swedentuxsteve

Put my name as "tux_steve" or "swe_tux_steve" in the credits.txt file

# SCP:SL Translation PR Template

## Language Name
Swedish

## State Type of change (New language, changed existing Etc.)
New language

# Checklist:
- [X] I have tested the translation changes ingame
- [X] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [X] I have made sure that I'm **not** submitting a duplicate translation 
- [X] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [X] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation

2020-09-26 14:06 UTC, Dat-Joseph commented
Please be sure to include all latest patches we made to our repo. There are still some missing files like abilities.txt, keybinds.txt etc...

2020-09-26 14:10 UTC, WinterBeyond commented on Translations/sv/Version_7-0-0.txt
> +Tryck på {KEYBINDING_INTERACTION} för att plocka upp <color=yellow>Weapon Manager-platta</color>.
Använd antingen `Weapon Manager-surfplatta` eller behåll `Weapon Manager Tablet`. Alternativ använd `Vapenhanterare-surfplatta` för en mer hel översättning.

2020-09-26 14:13 UTC, WinterBeyond commented on Translations/sv/Summary.txt
> +De ansvarar för har dödat [summary_scpfrags] personer.
Ändra `för har dödat` till `för att ha dödat`.

2020-09-26 14:14 UTC, WinterBeyond commented on Translations/sv/Summary.txt
> +All Stiftelse-säkerhet har avslutats.
`All säkerhetspersonal har utplånats.`

2020-09-26 14:18 UTC, WinterBeyond commented on Translations/sv/SCP079.txt
> +AUXILIAKRAFT
`AUXILIÄRKRAFT`

2020-09-26 14:20 UTC, WinterBeyond commented on Translations/sv/SCP079.txt
> +KLICKA PÅ [KEY] ATT VÄXLA KAMERA I ÖVERVAKNINGSKARTAN
Ändra `ATT VÄXLA KAMERA I ÖVERVAKNINGSKARTAN` till `FÖR ATT VISA ÖVERVAKNINGSKARTAN`

2020-09-26 14:22 UTC, WinterBeyond commented on Translations/sv/NewMainMenu.txt
> +AUTENTISERANDE
`AUTENTISERAR`

2020-09-26 14:23 UTC, WinterBeyond commented on Translations/sv/NewMainMenu.txt
> +<color=green>Kontakt etablerad</color>
Ändra `kontakt` till `anslutning`

2020-09-26 14:25 UTC, WinterBeyond commented on Translations/sv/NewMainMenu.txt
> +Joina om
`Återanslut`

2020-09-26 14:26 UTC, WinterBeyond commented on Translations/sv/NewInventory.txt
> +Painkillers:Relieve minor injuries.
`Åtgärda mindre skador.`

2020-09-26 14:27 UTC, WinterBeyond commented on Translations/sv/NewInventory.txt
> +Avväpnare:Vänsterklicka avväpnar, högerklickar släpper loss.\nHåll E på någon som är avväpnad i ditt team för att befria dem.
Ändra `team` till `lag`

2020-09-26 14:29 UTC, WinterBeyond commented on Translations/sv/NewInventory.txt
> +MTF Kommandör Kort:No description
`Kommendör`

2020-09-26 14:32 UTC, WinterBeyond commented on Translations/sv/MainMenu.txt
> +INGEN SERVRAR TILLGÄNGLIGA
Ändra `INGEN` till `INGA`

2020-09-30 16:31 UTC, OneKoin requested changes
You should add ones that are updated too

2020-10-03 17:16 UTC, Rnen commented
![image](https://user-images.githubusercontent.com/10668020/94997638-d4584300-05ac-11eb-9612-5e75609deb5b.png)
Please attend these issues

2020-10-31 12:57 UTC, Dat-Joseph commented
Hello swedentuxsteve,
you did not reply to us in the past month to the earlier mentioned issues. 
Could you please resolve them within a week? If you cannot do that, we are going to close this pullrequest.
We recommend to resolve the mentioned issues before re-opening this pull request.
Thank you.

2021-02-01 12:46 UTC, Rnen commented
No response, closing.

2021-02-01 12:46 UTC, closed without merging