[RU] Updated Localization
northwood-studios/SCPSL-Translations pull request #618
Opened 2020-09-11 17:05 UTC by REALMWTH

# SCP:SL Translation PR Template

## Language Name
Russian

## State Type of change (New language, changed existing Etc.)
Changed existing Russian translation

# Checklist:
- [ ] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation

2020-09-11 17:07 UTC, REALMWTH commented
@zabszk 
One check failed because of missed one line in Intercom_Door_Sign.txt because it's unnecessary of being translated for Russian language. Also, one more question: will Workstation be translateable too? It's not that hard as I've explained in Issues.

2020-09-11 21:52 UTC, zabszk commented
> 
> 
> @zabszk
> One check failed because of missed one line in Intercom_Door_Sign.txt because it's unnecessary of being translated for Russian language. So, I think that automated TranslationChecker action needs a bit rewrite.
> Also, one more question: will Workstation be translateable too? It's not that hard as I've explained in Issues.
> 
> @GuyFawkes76 please, review the changes ;)

Yeah, I'm aware about that TranslationChecker issue, it will be fixed really soon. For now we can simply ignore that.
I wanted to make workstations translatable in the incoming version, but they are quite complex. They will be translatable in the future for sure.

2020-09-11 22:12 UTC, GuyFawkes76 requested changes
Please, implement desired changes.

2020-09-11 22:12 UTC, GuyFawkes76 commented on Translations/ru/Badges.txt
> +SCP:SL Звуковой Менеджер
"Звуковой менеджер" doesn't sound well. Even if you Google it, you won't find job applications. It could be "Менеджер звукового дизайна" or "Менеджер саунд-дизайна" or something even better than those.

2020-09-11 22:12 UTC, GuyFawkes76 commented on Translations/ru/Intercom.txt
> +ИНТЕРКОМ ИСПОЛЬЗУЕТСЯ\nАДМИНИСТРАТОМ СЕРВЕРА
"Администратом" is definitely not right.

2020-09-13 05:05 UTC, REALMWTH commented on Translations/ru/Intercom.txt
> +ИНТЕРКОМ ИСПОЛЬЗУЕТСЯ\nАДМИНИСТРАТОМ СЕРВЕРА
@GuyFawkes76 fixed both issues

2020-09-13 14:49 UTC, GuyFawkes76 approved these changes

2020-09-15 08:57 UTC, merged