Added more sense to some translations
northwood-studios/SCPSL-Translations pull request #659
Opened 2020-10-31 21:02 UTC by DexlerXD

# SCP:SL Translation PR Template

## Language Name
Russian

## State Type of change (New language, changed existing Etc.)
I changed some translations, because of a little misunderstanding of some phrases, in mine opinion.

# Checklist:
- [X] I have tested the translation changes ingame
- [X] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [X] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [X] I have made sure that I'm **not** submitting a duplicate translation 
- [X] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [X] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation

2020-11-10 17:12 UTC, REALMWTH commented
@GuyFawkes76 please review

2020-11-12 13:16 UTC, GuyFawkes76 requested changes

2020-11-12 13:16 UTC, GuyFawkes76 commented on Translations/ru/HID_Sign.txt
> +ОСОБОГО
"Особого персонала" звучит странно. Предлагаю или переделать в "уполномоченного персонала" или ещё во что-нибудь.

2020-11-12 13:16 UTC, GuyFawkes76 commented on Translations/ru/NewMainMenu.txt
> +Секунда
В чём разница?

2020-11-12 13:16 UTC, GuyFawkes76 commented on Translations/ru/NewMainMenu.txt
> +Не отслеживать (Do not track)
Лучше в скобках оставить и полную расшифровку и аббревиатуру.

2020-11-12 13:16 UTC, GuyFawkes76 commented on Translations/ru/Nuke_Silo_Sign.txt
> +РАКЕТНАЯ
Она всё таки боеголовка, а не ракета, поэтому называть место её хранения ракетной шахтой, на мой взгляд, не совсем корректно.

2020-11-12 15:01 UTC, DexlerXD commented on Translations/ru/HID_Sign.txt
> +ОСОБОГО
Я хотел сделать уполномоченного, но это вылезает за строчку и выглядит плохо, ничего другого в голову не пришло пока.

2020-11-12 15:03 UTC, DexlerXD commented on Translations/ru/NewMainMenu.txt
> +Не отслеживать (Do not track)
Думал что будет вылезать из формата в игре, но сейчас проверил, более менее нормально. Исправлю.

2020-11-13 12:20 UTC, GuyFawkes76 commented
Не обязательно создавать новый реквест каждый раз, можно **и нужно** просто продолжить этот.

2020-11-13 14:29 UTC, DexlerXD commented
@GuyFawkes76 прошу вас оценить новые версии перевода

2021-02-01 13:45 UTC, GuyFawkes76 approved these changes

2021-02-02 10:40 UTC, merged