Yet another Finnish patch.
northwood-studios/SCPSL-Translations pull request #736
Opened 2021-04-01 23:11 UTC by Tuulipommi

# SCP:SL Translation PR Template

Edited Nuke translation, and added a new author to the manifest.

## Language Name
Finnish

## State Type of change (New language, changed existing Etc.)
Changed existing language.

# Checklist:
- [ ] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2021-04-01 23:14 UTC, Tuulipommi commented
Welp, someone help me format the manifest file.

2021-04-05 08:58 UTC, Tuulipommi commented
Edited the rest of the parts about Alpha Warhead fully to finnish.

2021-04-10 17:13 UTC, Foxeworks requested changes
just a few quick notes

2021-04-10 17:13 UTC, Foxeworks commented on Translations/fi/Badges.txt
> +Northwoodin Palaute Tiimi
```suggestion
Northwood Palautetiimi
```
Maybe change to just **Northwood** since all other titles are **Northwood _job name_** and combine words?

2021-04-10 17:13 UTC, Foxeworks commented on Translations/fi/Badges.txt
> +Northwoodin Varmennusvastaavien Valvoja
```suggestion
Northwood Varmennusvastaavavalvoja
```
Maybe change to just **Northwood** since all other titles are **Northwood _job name_**, and also combine the last word to make it look better?

2021-04-10 17:13 UTC, Foxeworks commented on Translations/fi/Badges.txt
> +SCP:SL virallisen Palvelimen Valvoja
```suggestion
SCP:SL Virallisen Palvelimen Valvoja
```

2021-04-10 17:13 UTC, Foxeworks commented on Translations/fi/Connection_Info.txt
> +Liitytään Palvelimelle
```suggestion
Liitytään palvelimelle
```
fair change, but maybe make it lowercase

2021-04-10 17:13 UTC, Foxeworks commented on Translations/fi/Connection_Info.txt
> +Liitytään Palvelimelle
```suggestion
Liitytään palvelimelle
```

2021-04-10 17:18 UTC, Tuulipommi commented on Translations/fi/Badges.txt
> +Northwoodin Varmennusvastaavien Valvoja
I mean, combining the two together in my mind makes it very confusing to read.

2021-04-10 17:20 UTC, Foxeworks commented on Translations/fi/Badges.txt
> +Northwoodin Varmennusvastaavien Valvoja
Yeah I guess that can be a bit more confusing, this'll work then

2021-04-10 17:22 UTC, Foxeworks submitted a review, later dismissed

2021-04-10 17:29 UTC, Foxeworks approved these changes

2021-04-10 17:30 UTC, merged