Update Abilities.txt  nl-BE
northwood-studios/SCPSL-Translations pull request #755
Opened 2021-04-29 11:30 UTC by JustCallMeQuincy

# SCP:SL Translation PR Template

## Language Name
Dutch

## State Type of change (New language, changed existing Etc.)
Fixed grammar

# Checklist:
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2021-04-29 15:24 UTC, RinTheWeeb requested changes
pls dont use google translate

2021-04-29 15:24 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Aanval (Woedend):Baan een weg om bij die te komen die je pijngedaan hebben. Je aanvallen vernietigen deuren en de meeste mensen in één klap.
Aanval (Woedend):Ren naar de mensen die jou hebben misdaan. Je aanvallen vernietigen deuren en doodden de meeste mensen in één klap.

2021-04-29 15:24 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Ultragevoelig:Je kan geen mensen zien tenzij ze rennen, tegen je botsen, of een wapen afvuren in je directe nabijheid.
directe nabijheid. -> directe omgeving.

2021-04-29 15:24 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Roofdier:Je voetstappen zijn onhoorbaar. Als je de aangegeven knop indrukt loop je sneller, maar maak je je bewegingen hoorbaar.
Je voetstappen zijn onhoorbaar. Als je de aangegeven knop indrukt loop je sneller, maar maakt je bewegingen hoorbaar.

2021-04-29 15:24 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Nadoen:Je kunt hardop praten met alle dichtstbijzijnde spelers, inclusief mensen.
Naäper is correct. 
You could also use: "Imitatie"

2021-04-29 15:24 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Geneesmiddel:Raakt een nabije mens aan, waardoor die onmiddelijk gedood wordt.
Raakt -> Raak

2021-04-29 15:24 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Open/Sluit Deuren:Je kan deuren bedienen om ze open en toe te doen voor 5 AP. Je kan ze ook vergrendelen, waardoor je AP gedraineerd wordt maar ervoor zorgt dat niemand de deur kan openen of sluiten
Open/Sluit Deuren:Je kan deuren sluiten en openen voor 5 AP. Je kan ze ook vergrendelen, waardoor je AP langzaam verbruikt wordt maar ervoor zorgt dat niemand de deur kan openen of sluiten totdat je de lockdown opzegt, of geen AP meer overhebt.

2021-04-29 15:24 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Lockdown:Vanaf Access Level 2, kan je sommige kamers bedienen om ze te vergrendelen, waardoor alle lichten uitgaan en de deuren sluiten. Wanneer mensen in een vergrendelde kamer zijn, kunnen ze SCP-1
Lockdown:Vanaf Access Level 2, kan je sommige kamers in een lockdown zetten, waardoor alle lichten uitgaan en de deuren sluiten. Wanneer mensen in een gelockdownde kamer zijn, kunnen ze SCP-173 niet zien, tenzij ze een zaklamp hebben.

2021-04-29 15:24 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Vrijwel Onverwoestbaar: Vijf generatoren zijn te vinden overheen de Heavy Containment Zone. Als ze allemaal ge-activeerd of vergrendeld zijn, zal je terug bedwongen worden.\nGeneratoren hebben een af
Vrijwel Onverwoestbaar: Vijf generatoren zijn over de Heavy Containment Zone verspreid. Als ze allemaal geactiveerd zijn, ga je dood.\nGeneratoren hebben een timer. Deze timer kan door andere spelers gestopt worden door op de "CANCEL"-knop te drukken op de generator.

2021-04-29 15:24 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Nek Breker:Klik of houd ingedrukt om de nek van een mens te breken, waardoor die onmiddelijk vermoord wordt voor zolang ze knipperen of ze je niet kunnen zien.
Nek Breker:Klik of houd de aanval knop ingedrukt om de nek van een mens te breken, waardoor die onmiddellijk vermoord wordt. Dit kan zolang ze knipperen of ze je niet kunnen zien.

2021-04-29 15:32 UTC, RinTheWeeb commented
> 
> 
> > pls dont use google translate
> 
> unnecessary. don't be petty.

If I was petty, I would not bother making all these review comments and just close the whole pull request.

2021-04-29 15:35 UTC, sirmeepington commented
> > > pls dont use google translate
> > 
> > 
> > unnecessary. don't be petty.
> 
> If I was petty, I would not bother making all these review comments and just close the whole pull request.

they'd both be petty. just one more petty than the other.

2021-04-29 15:37 UTC, RinTheWeeb commented
> 
> 
> > > > pls dont use google translate
> > > 
> > > 
> > > unnecessary. don't be petty.
> > 
> > 
> > If I was petty, I would not bother making all these review comments and just close the whole pull request.
> 
> they'd both be petty. just one more petty than the other.

What's petty is saying you love drama, and when you are in public now claiming i'm the petty one. 👍

2021-04-29 15:37 UTC, JustCallMeQuincy commented on Translations/nl/Abilities.txt
> +Scopofobie:Je begint handelbaar, en wordt woedend wanneer je gezien of verwond wordt. Underdruk je woede door overtreders te vermoorden - volg hun licht vóór je woede bekoelt. De vernedering van elke
"De dood van elke overtreder geeft je extra AHP"
In the official translations (and in the game itself), each person that looks at you gives you more AHP, not each kill you get.

2021-04-29 15:39 UTC, sirmeepington commented
> > > > > pls dont use google translate
> > > > 
> > > > 
> > > > unnecessary. don't be petty.
> > > 
> > > 
> > > If I was petty, I would not bother making all these review comments and just close the whole pull request.
> > 
> > 
> > they'd both be petty. just one more petty than the other.
> 
> What's petty is saying you love drama, and when you are in public now claiming i'm the petty one. 👍

i love drama and i'll clearly say it. and you _are_ the petty one here. don't deflect this onto me.

2021-04-29 15:41 UTC, JustCallMeQuincy commented on Translations/nl/Abilities.txt
> +Aanval (Woedend):Baan een weg om bij die te komen die je pijngedaan hebben. Je aanvallen vernietigen deuren en de meeste mensen in één klap.
It's about the attack and about destroying doors, I think it's more appropriate to leave it at "Baan een weg" since that refers to doors being destroyed instead of just running.

2021-04-29 15:42 UTC, sirmeepington commented
> > > > > > > pls dont use google translate
> > > > > > 
> > > > > > 
> > > > > > unnecessary. don't be petty.
> > > > > 
> > > > > 
> > > > > If I was petty, I would not bother making all these review comments and just close the whole pull request.
> > > > 
> > > > 
> > > > they'd both be petty. just one more petty than the other.
> > > 
> > > 
> > > What's petty is saying you love drama, and when you are in public now claiming i'm the petty one. 👍
> > 
> > 
> > i love drama and i'll clearly say it. and you _are_ the petty one here. don't deflect this onto me.
> 
> You have NOTHING to do with this whole PR. The only reason you are here is because I am. Don't even talk about who is petty here.

I'm here as it was linked in the staff server, by you.

2021-04-29 15:44 UTC, AgentBlackout commented
poo poo fard

2021-04-29 15:44 UTC, JustCallMeQuincy commented on Translations/nl/Abilities.txt
> +Roofdier:Je voetstappen zijn onhoorbaar. Als je de aangegeven knop indrukt loop je sneller, maar maak je je bewegingen hoorbaar.
"Als je de aangegeven knop indrukt loop je sneller, maar maakt je bewegingen hoorbaar." This sentence isn't correct. a good alternative would be "Als je de aangegeven knop indrukt loop je sneller, maar worden je bewegingen hoorbaar."

2021-04-29 15:48 UTC, JustCallMeQuincy commented on Translations/nl/Abilities.txt
> +Nadoen:Je kunt hardop praten met alle dichtstbijzijnde spelers, inclusief mensen.
"Mimic:You can speak out loud to any nearby players, including humans." It's about the noun, not the verb. Though it would be correct, I tried to keep it close to the original translations.

2021-04-29 15:49 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Scopofobie:Je begint handelbaar, en wordt woedend wanneer je gezien of verwond wordt. Underdruk je woede door overtreders te vermoorden - volg hun licht vóór je woede bekoelt. De vernedering van elke
Correct, then it should be:

Scopofobie:Je begint kalm. Je wordt woedend wanneer je in je gezicht wordt aangekeken of wanneer je verwond wordt. Onderdruk je woede door overtreders te vermoorden - volg hun hartslag vóór je woede afneemt. Elk mens dat jou aankijkt geeft je extra AHP, dit voorkomt alle verwondingen zolang je die hebt.

2021-04-29 15:50 UTC, JustCallMeQuincy commented on Translations/nl/Abilities.txt
> +Geneesmiddel:Raakt een nabije mens aan, waardoor die onmiddelijk gedood wordt.
"Antidote:Touches a human within close range, instantly killing them." Either one would be fine, but I tried to keep it close to the original translations. Here it's "Raakt aan" instead of "Raak aan".

2021-04-29 15:51 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Aanval (Woedend):Baan een weg om bij die te komen die je pijngedaan hebben. Je aanvallen vernietigen deuren en de meeste mensen in één klap.
"Baan een weg" is used when you need to go from place A to B. It doesn't really sound well in this context, but that's my opinion.

2021-04-29 15:54 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Roofdier:Je voetstappen zijn onhoorbaar. Als je de aangegeven knop indrukt loop je sneller, maar maak je je bewegingen hoorbaar.
Both your suggestion and mine are correct.

2021-04-29 15:54 UTC, JustCallMeQuincy commented on Translations/nl/Abilities.txt
> +Lockdown:Vanaf Access Level 2, kan je sommige kamers bedienen om ze te vergrendelen, waardoor alle lichten uitgaan en de deuren sluiten. Wanneer mensen in een vergrendelde kamer zijn, kunnen ze SCP-1
"Wanneer mensen in een gelockdownde kamer zijn" I'm afraid "gelockdownde" doesn't exist as far as I can tell. You could however use "zo'n kamer" to refer to "kan je sommige kamers in een lockdown zetten".

"Wanneer mensen in zo'n kamer zijn, kunnen ze SCP-173 niet zien, tenzij ze een zaklamp hebben."

2021-04-29 15:57 UTC, JustCallMeQuincy commented on Translations/nl/Abilities.txt
> +Nek Breker:Klik of houd ingedrukt om de nek van een mens te breken, waardoor die onmiddelijk vermoord wordt voor zolang ze knipperen of ze je niet kunnen zien.
"Hold or click to snap a human's neck" there is no key given, there is probably a reason for that.

2021-04-29 15:58 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Nadoen:Je kunt hardop praten met alle dichtstbijzijnde spelers, inclusief mensen.
"Nadoen" is a verb as well.
"Imitatie"/"Imiteren" fits SCP-939 the best imo.

2021-04-29 16:03 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Geneesmiddel:Raakt een nabije mens aan, waardoor die onmiddelijk gedood wordt.
Yeah you're correct. 
Since the original translation is describing what the Antidote will do, Raakt is correct.

2021-04-29 16:06 UTC, RinTheWeeb commented on Translations/nl/Abilities.txt
> +Lockdown:Vanaf Access Level 2, kan je sommige kamers bedienen om ze te vergrendelen, waardoor alle lichten uitgaan en de deuren sluiten. Wanneer mensen in een vergrendelde kamer zijn, kunnen ze SCP-1
"gelockdownde" is a word nowadays since the corona crisis. You'll find many newspapers using this word. And it would fit nicely in this sentence.

2021-04-29 16:28 UTC, JustCallMeQuincy commented on Translations/nl/Abilities.txt
> +Aanval (Woedend):Baan een weg om bij die te komen die je pijngedaan hebben. Je aanvallen vernietigen deuren en de meeste mensen in één klap.
It's an expression: 'Zich een weg banen door' which means: 'een pad maken waar er geen was'
"Tear through anything in your way", actually breaking/shoving stuff to get through.
It's probably different in our countries.

2021-04-29 16:30 UTC, JustCallMeQuincy commented on Translations/nl/Abilities.txt
> +Nadoen:Je kunt hardop praten met alle dichtstbijzijnde spelers, inclusief mensen.
I agree

2021-04-29 16:44 UTC, JustCallMeQuincy commented on Translations/nl/Abilities.txt
> +Roofdier:Je voetstappen zijn onhoorbaar. Als je de aangegeven knop indrukt loop je sneller, maar maak je je bewegingen hoorbaar.
"Als je de aangegeven knop indrukt loop je sneller, maar maakt je bewegingen hoorbaar." doesn't sound correct to me.
"Als je de aangegeven knop indrukt loop je sneller, maar dit maakt je bewegingen hoorbaar." does.

I could be wrong, of course, but the people I've asked share my opinion.

2021-07-05 11:30 UTC, RinTheWeeb commented
Closing PR since no changes are made.

2021-07-05 11:30 UTC, closed without merging