[RU] Translation update for version 11.0
northwood-studios/SCPSL-Translations pull request #777
Opened 2021-07-12 21:02 UTC by REALMWTH

# SCP:SL Translation PR Template

## Language Name
Russian

## State Type of change (New language, changed existing Etc.)
Updated Russian localization for 11.0 patch

# Checklist:
- [ ] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2021-07-12 21:34 UTC, REALMWTH commented
There are some of the issues within the game that prevents correct quality translation:
https://github.com/northwood-studios/SCPSL-Translations/issues/778
https://github.com/northwood-studios/SCPSL-Translations/issues/779

2021-07-13 20:32 UTC, GuyFawkes76 requested changes
Кроме того, что указал отдельными комментариями, ещё есть сомнения в падежах в файле Categories и в случае Повстанцев Хаоса. (У меня сейчас нет возможности проверить в игре, поэтому просто проверьте ещё раз, что всё ок)

2021-07-13 20:32 UTC, GuyFawkes76 commented on Translations/ru/Class_Names.txt
> +Повстанцев Хаоса — Репрессор
Усмиритель? Но, в принципе, можно оставить и так.

2021-07-13 20:32 UTC, GuyFawkes76 commented on Translations/ru/Class_Names.txt
> +Повстанцев Хаоса — Последователь
Не думаю, что Последователь - правильное слово здесь для обозначения слова Conscript

2021-07-13 20:32 UTC, GuyFawkes76 commented on Translations/ru/NewMainMenu.txt
> +Эти изменения требуют перезапуск меню.\nПерезагрузить меню сейчас?
Возможно, "перезапуска"?

2021-07-15 06:52 UTC, REALMWTH commented on Translations/ru/NewMainMenu.txt
> +Эти изменения требуют перезапуск меню.\nПерезагрузить меню сейчас?
Исправлено

2021-07-15 06:53 UTC, REALMWTH commented on Translations/ru/Class_Names.txt
> +Повстанцев Хаоса — Последователь
Заменил на Новобранец

2021-07-15 06:53 UTC, REALMWTH commented on Translations/ru/Class_Names.txt
> +Повстанцев Хаоса — Репрессор
Оставил как есть

2021-07-15 06:54 UTC, REALMWTH commented
@GuyFawkes76 по падежам всё просто. Формат сообщения в hint'e:
Достигнут лимит <color=yellow>[type]</color>

Пример: Достигнут лимит Раций

2021-07-25 17:18 UTC, GuyFawkes76 approved these changes

2021-07-25 17:19 UTC, merged