[RU] Translation update for Patreon Beta v.11.0
northwood-studios/SCPSL-Translations pull request #795
Opened 2021-07-26 02:24 UTC by REALMWTH

# SCP:SL Translation PR Template

## Language Name
Russian

## State Type of change (New language, changed existing Etc.)
Updated Russian localization for Patreon Beta version 11.0
Tested in-game, everything looks fine

# Checklist:
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2021-07-30 16:31 UTC, GuyFawkes76 requested changes
Исправить указанные, плюс два файла почти полностью не переведены.

2021-07-30 16:31 UTC, GuyFawkes76 commented on Translations/ru/Class_Bio.txt
> +Устрашающий облик SCP-173 привлекает внимание. Скульптура становится смертельно опасной пока на неё не смотрят, однако она постоянно требует к себе внимания.
"однако она постоянно требует к себе внимания" - звучит неестественно, лучше заменить.

2021-07-30 16:31 UTC, GuyFawkes76 commented on Translations/ru/MainMenu.txt
> +Отображает точное число здоровья вместо процентов.
Может, не "число", а "количество"?

2021-07-30 16:31 UTC, GuyFawkes76 commented on Translations/ru/NewMainMenu.txt
> +Декали
Возможно, можно подобрать лучшее слово, но, может быть, и нет :)

2021-07-31 08:46 UTC, REALMWTH commented on Translations/ru/MainMenu.txt
> +Отображает точное число здоровья вместо процентов.
Имеется ввиду: числом, а не процентом

2021-07-31 08:48 UTC, REALMWTH commented on Translations/ru/Abilities.txt
> +Головокружительная Скорость:Не важно где они прячутся, совсем скоро вы их всех найдёте, а они даже не успеют вас увидеть. Удвойте вашу скорость передвижение и дистанцию телепортации, но вы станете бо
Исправлено

2021-07-31 08:59 UTC, REALMWTH commented on Translations/ru/NewMainMenu.txt
> +Декали
Другое тут сложно придумать.
http://www.gamedev.ru/terms/Decal

2021-07-31 09:01 UTC, REALMWTH commented on Translations/ru/Class_Bio.txt
> +Устрашающий облик SCP-173 привлекает внимание. Скульптура становится смертельно опасной пока на неё не смотрят, однако она постоянно требует к себе внимания.
Перефразировал
"Несмотря на то, что скульптура постоянно требует к себе внимания, она смертельно опасна только тогда, когда на неё не смотрят."

2021-07-31 09:04 UTC, REALMWTH commented on Translations/ru/Abilities.txt
> +Рывок (Ярость):Уничтожьте своих обидчиков как можно скорее - они этого заслуживают. Вы устремляетесь вперёд, уничтожая всё на своём пути. Если вы встречаетесь с тяжёлыми воротами, вы можете проломить
Перефразировал
"Если перед вами появятся тяжёлые ворота, вы можете проломить их."

2021-07-31 09:06 UTC, REALMWTH commented on Translations/ru/Abilities.txt
> +Железобетон:Позвольте им восхищаться вами, но не давайте им заниматься вандализмом. Вы более стойки к огнестрельному урону. Оружие с низкой пробивной способностью наносит намного меньше урона в сравн
Исправлено

2021-07-31 09:12 UTC, REALMWTH commented on Translations/ru/Abilities.txt
> +Моргание:Заставьте их пожалеть о том, что перестали на вас смотреть, даже если на мгновение. Когда индикатор-глаз становится тёмно-красным, наведите его на желаемую позицию. Отпустите клавишу чтобы т
Перефразировал так
"Не позволяйте им ни на мгновение переставать смотреть на вас."

2021-08-05 20:17 UTC, GuyFawkes76 requested changes
Требуется исправить указанное.

2021-08-05 20:17 UTC, GuyFawkes76 commented on Translations/ru/AttachmentNames.txt
> +Удлинённое Дуло~Немного уменьшает радиус разброса, но увеличивает общий вес и длину огнестрельного оружия.
Дуло -> Ствол. Мне кажется, можно оставить просто разброс, без радиуса. "Огнестрельного" тоже можно убрать, и так понятно, о чём речь.

2021-08-05 20:17 UTC, GuyFawkes76 commented on Translations/ru/AttachmentParameters.txt
> +Согласованность паттерна
Постоянство осыпи

2021-08-05 20:17 UTC, GuyFawkes76 commented on Translations/ru/Class_Bio.txt
> +Устрашающий облик SCP-173 привлекает внимание. Несмотря на то, что скульптура постоянно требует к себе внимания, она смертельно опасна только тогда, когда на неё не смотрят.
В текущем варианте с "Несмотря на" я не вижу никакой логики. Предлагаю заменить второе предложение на "Скульптура постоянно требует к себе внимания, потому что она смертельно опасна тогда, когда на неё не смотрят.". 
Или же на "Скульптура смертельно опасна тогда, когда на неё не смотрят, поэтому она постоянно требует к себе внимания."

2021-08-05 20:17 UTC, GuyFawkes76 commented on Translations/ru/MainMenu.txt
> +Отображает точное число здоровья вместо процентов.
"Количество" не подразумевает величину в процентах, поэтому я всё ещё считаю, что сюда лучше подойдёт оно. (Только в 85 строк. В 84 так и оставить!)

2021-08-06 21:28 UTC, REALMWTH commented on Translations/ru/Abilities.txt
> +Головокружительная Скорость:Не важно где они прячутся, совсем скоро вы их всех найдёте, а они даже не успеют вас увидеть. Удвойте вашу скорость передвижения и дистанцию телепортации, но вы станете бо
Исправлено

2021-08-06 21:29 UTC, REALMWTH commented on Translations/ru/Abilities.txt
> +Рывок (Ярость):Уничтожьте своих обидчиков как можно скорее - они этого заслуживают. Вы устремляетесь вперёд, уничтожая всё на своём пути. Если перед вами появятся тяжёлые ворота, вы можете проломить
Исправлено

2021-08-06 21:30 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Прицес С Точкой~Рефлекторный прицел без увеличения с маленькой светящейся точкой, указывающей на место прицеливания.
Исправлено

2021-08-06 21:30 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Мушка~Пара маркеров регулировки, составляющие простое и легкое прицельное приспособление.
Исправлено

2021-08-06 21:32 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Стандартное Дуло~Обычное дуло без насадок.
Исправлено

2021-08-06 21:32 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Удлинённое Дуло~Повышает общую огневую мощь, но снижает подвижность из-за увеличенного веса и длины
Исправлено

2021-08-06 21:33 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +AP Магазин~Стандартный магазин, содержащий бронепробивающие пули.
Исправлено

2021-08-06 21:34 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +FMJ Магазин~Стандартный магазин, содержащий пули в цельнометаллической оболочке.
Исправлено

2021-08-06 21:34 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +JHP Магазин~Стандартный магазин, содержащий пустотелые пули.
Исправлено

2021-08-06 21:35 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +4-Зарядный Цилиндр~Вмещает меньше патронов, но способен наносить повышенный урон бронированным противникам.
Исправлено

2021-08-06 21:35 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Карабинная Ствольная Коробка~Обычная верхняя стволовая коробка карабина, которая считается отличным компромиссом между огневой мощью и подвижностью.
Исправлено

2021-08-06 21:36 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Короткое Дуло~Укороченный вариант стандартного ствола, используемый для повышения скорости взятия оружия и подвижности.
Исправлено

2021-08-06 21:37 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Удлинённое Дуло~Немного уменьшает радиус разброса, но увеличивает общий вес и длину огнестрельного оружия.
Исправлено

2021-08-06 21:38 UTC, REALMWTH commented on Translations/ru/MainMenu.txt
> +Отображает точное число здоровья вместо процентов.
Зачем оставлять HP в 84-й строке?

2021-08-06 21:41 UTC, REALMWTH commented on Translations/ru/AttachmentParameters.txt
> +Согласованность паттерна
Не согласен. Это не будет понятно рядовому игроку.

2021-08-06 21:41 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Чок~Увеличивает общий радиус распространения, но улучшает согласованность паттерна.
Не согласен. Это не будет понятно рядовому игроку.

2021-08-06 21:42 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Глушитель~Регулятор звука. Уменьшает громкость выстрелов, но увеличивает общий вес и длину огнестрельного оружия.
Всё же считаю, что "Глушитель" будет куда легче для восприятия.

2021-08-06 21:42 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Рукоятка~Вертикальная передняя рукоятка. Облегчает работу с подъемом дула.
Предлагаю такой вариант: "Облегчает контроль над вертикальной отдачей."

2021-08-06 21:45 UTC, REALMWTH commented on Translations/ru/Class_Bio.txt
> +Устрашающий облик SCP-173 привлекает внимание. Несмотря на то, что скульптура постоянно требует к себе внимания, она смертельно опасна только тогда, когда на неё не смотрят.
Предлагаю такой вариант: "Скульптура смертельна опасна пока на неё не смотрят, так как она постоянно требует к себе внимания."

2021-08-06 21:49 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Глушитель~Регулятор звука. Уменьшает громкость выстрелов, но увеличивает общий вес и длину огнестрельного оружия.
Исправлено

2021-08-21 18:09 UTC, GuyFawkes76 requested changes

2021-08-21 18:09 UTC, GuyFawkes76 commented on Translations/ru/Class_Bio.txt
> +Устрашающий облик SCP-173 привлекает внимание. Скульптура смертельна опасна пока на неё не смотрят, так как она постоянно требует к себе внимания.
Причинно-следственная связь нарушена. "Так как" следует заменить на "поэтому".
Плюс, пропущена запятая перед "пока".

2021-08-21 18:09 UTC, GuyFawkes76 commented on Translations/ru/Class_Descriptions.txt
> +Убейте всех.\nНе дайте никому сбежать.\nКооперируйтесь с другими <color=#F00>объектами SCP.</color><color=#FFFF00>\nУдерживайте клавишу направления взгляда\nпока на вас смотрят чтобы телепортироватьс
Пропущена запятая перед "чтобы".

2021-08-21 18:09 UTC, GuyFawkes76 commented on Translations/ru/Class_Descriptions.txt
> +Убейте всех.\nНе дайте никому сбежать.\nКооперируйтесь с другими <color=#F00>объектами SCP.</color><color=#FFFF00>\nНажмите левую клавишу мыши чтобы мгновенно убить вашего противника.\nВзаимодействуй
Два раза пропущены запятые перед "чтобы".

2021-08-21 18:09 UTC, GuyFawkes76 commented on Translations/ru/Class_Descriptions.txt
> +Убейте всех.\nНе дайте никому сбежать.\nКооперируйтесь с другими <color=#F00>объектами SCP.</color><color=#FFFF00>\nНажмите левую клавишу мыши чтобы с небольшой задержкой нанести удар по противнику.<
Запятая перед "чтобы".

2021-08-21 18:09 UTC, GuyFawkes76 commented on Translations/ru/AttachmentNames.txt
> +Удлинённый Ствол~Немного уменьшает разброс пуль, но увеличивает общий вес и длину огнестрельного оружия.
Убрать "огнестрельного", нет нужды это упоминать, и так понятно, что не холодного.

2021-08-22 13:33 UTC, REALMWTH commented on Translations/ru/Class_Descriptions.txt
> +Убейте всех.\nНе дайте никому сбежать.\nКооперируйтесь с другими <color=#F00>объектами SCP.</color><color=#FFFF00>\nНажмите левую клавишу мыши чтобы с небольшой задержкой нанести удар по противнику.<
Исправлено

2021-08-22 13:34 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Удлинённый Ствол~Немного уменьшает разброс пуль, но увеличивает общий вес и длину огнестрельного оружия.
Исправлено

2021-08-22 13:35 UTC, REALMWTH commented on Translations/ru/Class_Descriptions.txt
> +Убейте всех.\nНе дайте никому сбежать.\nКооперируйтесь с другими <color=#F00>объектами SCP.</color><color=#FFFF00>\nНажмите левую клавишу мыши чтобы мгновенно убить вашего противника.\nВзаимодействуй
Исправлено

2021-08-22 13:35 UTC, REALMWTH commented on Translations/ru/Class_Descriptions.txt
> +Убейте всех.\nНе дайте никому сбежать.\nКооперируйтесь с другими <color=#F00>объектами SCP.</color><color=#FFFF00>\nУдерживайте клавишу направления взгляда\nпока на вас смотрят чтобы телепортироватьс
Исправлено

2021-08-22 13:36 UTC, REALMWTH commented on Translations/ru/Class_Bio.txt
> +Устрашающий облик SCP-173 привлекает внимание. Скульптура смертельна опасна пока на неё не смотрят, так как она постоянно требует к себе внимания.
Исправлено

2021-08-22 13:37 UTC, REALMWTH commented
Добавил перевод текста из этого PR
https://github.com/northwood-studios/SCPSL-Translations/pull/852

2021-08-22 15:54 UTC, GuyFawkes76 requested changes

2021-08-22 15:54 UTC, GuyFawkes76 commented on Translations/ru/AttachmentNames.txt
> +Чок~Увеличивает общий радиус рассеивания, но улучшает согласованность паттерна.
Нет такой вещи, как "согласованность паттерна". Согласованность с кем? Это не имеет смысла. В который раз предлагаю "постоянство паттерна".

2021-08-22 15:54 UTC, GuyFawkes76 commented on Translations/ru/Class_Bio.txt
> +Устрашающий облик SCP-173 привлекает внимание. Скульптура смертельна опасна пока на неё не смотрят, потому что она постоянно требует к себе внимания.
Здесь должно быть не "потому что", а "поэтому". 
Смысл: Скульптура опасна, когда на неё не смотрят, следовательно (поэтому, а не потому что) на неё надо смотреть (она требует к себе внимания).

2021-08-22 15:54 UTC, GuyFawkes76 commented on Translations/ru/Class_Descriptions.txt
> +Убейте всех.\nНе дайте никому сбежать.\nКооперируйтесь с другими <color=#F00>объектами SCP.</color><color=#FFFF00>\nУдерживайте клавишу направления взгляда\nпока на вас смотрят, чтобы телепортировать
Пропущена запятая перед "пока на вас смотрят".

2021-08-22 15:54 UTC, GuyFawkes76 commented on Translations/ru/Class_Descriptions.txt
> +Убейте всех.\nНе дайте никому сбежать.\nКооперируйтесь с другими <color=#F00>объектами SCP.</color><color=#FFFF00>\nНажмите левую клавишу мыши, чтобы мгновенно убить вашего противника.\nВзаимодейству
Нужна запятая перед "чтобы излечить".

2021-08-22 15:54 UTC, GuyFawkes76 commented on Translations/ru/AttachmentParameters.txt
> +Согласованность паттерна
Предлагаю "постоянство паттерна", потому что "согласованность паттерна" не имеет смысла.

2021-08-22 23:20 UTC, REALMWTH commented on Translations/ru/AttachmentNames.txt
> +Чок~Увеличивает общий радиус рассеивания, но улучшает согласованность паттерна.
Исправлено

2021-08-22 23:21 UTC, REALMWTH commented on Translations/ru/Class_Bio.txt
> +Устрашающий облик SCP-173 привлекает внимание. Скульптура смертельна опасна пока на неё не смотрят, потому что она постоянно требует к себе внимания.
Исправлено

2021-08-22 23:25 UTC, REALMWTH commented on Translations/ru/Class_Descriptions.txt
> +Убейте всех.\nНе дайте никому сбежать.\nКооперируйтесь с другими <color=#F00>объектами SCP.</color><color=#FFFF00>\nУдерживайте клавишу направления взгляда\nпока на вас смотрят, чтобы телепортировать
Исправлено, хоть и не понятно, зачем добавлять запятую, если между двумя частями предложения есть новая строка

2021-08-22 23:25 UTC, REALMWTH commented on Translations/ru/Class_Descriptions.txt
> +Убейте всех.\nНе дайте никому сбежать.\nКооперируйтесь с другими <color=#F00>объектами SCP.</color><color=#FFFF00>\nНажмите левую клавишу мыши, чтобы мгновенно убить вашего противника.\nВзаимодейству
Исправлено, хоть и не понятно, зачем добавлять запятую, если между двумя частями предложения есть новая строка

2021-08-22 23:28 UTC, REALMWTH commented on Translations/ru/AttachmentParameters.txt
> +Согласованность паттерна
Исправлено

2021-08-28 07:18 UTC, GuyFawkes76 approved these changes

2021-09-05 20:05 UTC, merged