Fixing text in-game
northwood-studios/SCPSL-Translations pull request #832
Opened 2021-08-06 12:16 UTC by MajorFox-MJ

- Fixing the button to force the round to start.

2021-08-12 14:52 UTC, M4st3r0re requested changes
J'ai passé au crible seulement la partie "Abilities". Traduction correcte dans l'ensemble. Des reformulations sont conseillées pour certaines parties mais de trop grosses prises de libertés ont quelquefois abouti à une perte totale du sens et des informations du texte original.

Les marques telles que "(information en trop)" etc, sont seulement à titre indicatif et représentent le plus gros problème de la version actuelle.

2021-08-12 14:52 UTC, M4st3r0re commented on Translations/fr/Abilities.txt
> +Réanimation:En maintenant le bouton d'interaction enfoncé pendant plusieurs secondes sur un cadavre récemment tué, vous le réanimerez en zombie. Ils ont une santé faible et une attaque faible, mais s
Nouvelle proposition: (importante) (informations fausses) (informations en trop)

Guérison:Réanimez un humain récemment tué. Les humain réanimés joueront en tant que zombie au mouvements rapides mais à la santé fragile.\nIl n’y a aucune limite d’êtres humains pouvant être réanimés.

2021-08-12 14:52 UTC, M4st3r0re commented on Translations/fr/Abilities.txt
> +Confinement:À partir du niveau d'accès 2, vous pouvez verrouiller certaines pièces ce qui éteindra toutes les lumières et bloquera toutes les issues. Cela fait les humains ne peuvent plus voir SCP-17
Correction de la dernière phrase:
"Cela fait les humains ne peuvent plus voir SCP-173."

Changement en:
Les humains se trouvant dans la salle à ce moment là ne peuvent plus voir SCP-173.

2021-08-12 14:52 UTC, M4st3r0re commented on Translations/fr/Abilities.txt
>  Pratiquement indestructible:Cinq générateurs apparaissent dans la zone de confinement intensif, nécessitant une carte de haut niveau et une tablette de gestion des armes pour être activés. La seule f
Nouvelle proposition: (informations en trop)

Pratiquement indestructible:Cinq générateurs apparaissent dans la zone de confinement intensif. Si tous sont déverrouillés et activés, vous serez reconfiné.\nLes générateurs disposent d'un compte à rebours que chaque joueur peut interrompre en appuyant sur un bouton à l'intérieur même du générateur concerné.

2021-08-12 18:13 UTC, MajorFox-MJ commented on Translations/fr/Abilities.txt
>  Pratiquement indestructible:Cinq générateurs apparaissent dans la zone de confinement intensif, nécessitant une carte de haut niveau et une tablette de gestion des armes pour être activés. La seule f
La prochaine mise à jour rend inutile toute modification jusqu'à la sortie du nouveau protocole de reconfinement.
Merci tout de même~

2021-08-12 18:39 UTC, MajorFox-MJ commented on Translations/fr/NewMainMenu.txt
> +<size=20><b>Créer une partie depuis le jeu n'est désormais plus supporté.\n\nIl y a cependant trois façons d'en créer une :\nVous pouvez télécharger le serveur dédié (SCP:SL dedicated server - Steam
L'information sera retirée.
> "donne un aperçu négatif de la fonctionnalité"
Cette fonctionnalité a été retirée car elle n'est plus supportée. Elle est automatiquement considérée une zone où tout report de bug sera ignoré.

2021-08-16 18:57 UTC, M4st3r0re submitted a review, later dismissed

2021-08-18 12:22 UTC, Dat-Joseph approved these changes

2021-08-18 12:22 UTC, merged