Updated translations for minor attachment editor changes
northwood-studios/SCPSL-Translations pull request #892
Opened 2021-09-26 09:40 UTC by zabszk

Updated all languages with Attachment Editor translated.

2021-09-26 10:36 UTC, MichalPetryka requested changes

2021-09-26 10:36 UTC, MichalPetryka commented on Translations/pl/AttachmentEditors.txt
> +ZESTAWY
Move unrelated changes to a separate PR

2021-09-26 10:36 UTC, MichalPetryka commented on Translations/English (default)/AttachmentEditors.txt
> +Preset #{0}
```suggestion
Preset #[index]
```
Use the named formats.

2021-09-26 10:55 UTC, zabszk commented on Translations/pl/AttachmentEditors.txt
> +ZESTAWY
They are not unrelated. This MR reworks AttachmentEditor file, so this is related. These strings are too long and don't fit the in-game workstations. It's pointless to make a fix that doesn't fix anything (strings still don't fit).

2021-09-28 15:31 UTC, Rnen commented on Translations/de/AttachmentEditors.txt
> +Voreinstellung #{0}
```suggestion
Voreinstellung #[index]
```

2021-09-28 15:31 UTC, Rnen commented on Translations/es/AttachmentEditors.txt
> +Preestablecido #{0}
```suggestion
Preestablecido #[index]
```

2021-09-28 15:31 UTC, Rnen commented on Translations/fr/AttachmentEditors.txt
> +Préréglage #{0}
```suggestion
Préréglage #[index]
```

2021-09-28 15:31 UTC, Rnen commented on Translations/pl/AttachmentEditors.txt
> +Zestaw {0}.
```suggestion
Zestaw #[index].
```

2021-09-28 15:31 UTC, Rnen commented on Translations/th/AttachmentEditors.txt
> +พรีเซ็ทที่ #{0}
```suggestion
พรีเซ็ทที่ #[index]
```

2021-09-28 15:31 UTC, Rnen commented on Translations/zh/AttachmentEditors.txt
> +预设 #{0}
```suggestion
预设 #[index]
```

2021-09-28 15:32 UTC, Rnen approved these changes

2021-09-28 15:33 UTC, merged