SCP:SL KOR
northwood-studios/SCPSL-Translations pull request #918
Opened 2021-10-27 13:21 UTC by SovietNakJi

# **SCP:SL Translation PR Template**
ko
## **Language Name**
Korea

## **State Type of change (New language, changed existing Etc.)**
The user added how to use the item comfortably
I modified the translation so smoothly
The spacing was weird, so I put it down naturally
My translation was interpreted naturally, unlike the previous one
I changed it to fit the parabellum(+ halloween)

Translators
Master(Me): SovietNakJi
Supporter: 죄천이

# **Checklist:**
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  (Exception to this is when edits has __only__ been made in-browser. If this is the case, also check this box.)
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure to **not** included any advertisements/pointers to non-game stuff other than the translation author in the credits file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2021-11-15 18:18 UTC, Rnen requested changes

2021-11-15 18:18 UTC, Rnen commented on Translations/ko/manifest.json
>  }
Any reason why people was removed from this file?

2021-11-17 13:16 UTC, SovietNakJi commented on Translations/ko/manifest.json
>  }
<Delete People>
Dr-Devan : He said he would quit this translation. And he said he was busy with work. I talked to him and told him that I would work on the translation.(I spoke to him on the phone, but if I ask him to do it, I can prove that he left it to me without further translation.

Arizen : He fought with Dr. Devon. The reason is that he posted Dr. Devan's translation as it was, but he forgot to ask Dr. Devan, so the misunderstanding was resolved, and he naturally stopped translating as he moved the content to another game.

schade : I know it was translated, but I tried to edit it and upload it because it wasn't natural, but he deleted the nickname by excluding other people's opinions, saying his translation was good. So I upload this Korean translation again. (It's good to feedback, but I think the comments are getting worse and worse due to his too much feedback and strong self-assertion.)

<Add People>
SovietNakJi(ME) : It's me

죄천이(Joe Cheon Lee) :  He helped improve the strange things and various problems of translation.

2021-11-17 13:24 UTC, SovietNakJi commented on Translations/ko/manifest.json
>  }
There's a reason.
If you ask me not to modify it, I'll prepare a file that won't be modified.

have good day

2021-12-28 22:11 UTC, Rnen submitted a review, later dismissed

2021-12-28 22:16 UTC, Rnen commented
![image](https://user-images.githubusercontent.com/10668020/147611063-04544b0f-43f1-40e8-85c7-44014b753156.png)

2021-12-28 22:16 UTC, merged

2022-01-03 14:51 UTC, SovietNakJi commented
Sorry! I think I made a mistake because it's been a while.