[RU] Updated to 11.1.2
northwood-studios/SCPSL-Translations pull request #967
Opened 2022-01-20 20:09 UTC by bladuk

# **SCP:SL Translation PR Template**

## **Language Name**
Russian

## **State Type of change (New language, changed existing Etc.)**
Changed existing
Added subtitles translation;
Added CHI's bio translation;
Updated death reasons translation;
Added disarming translation;
Added SCP-330's bag, SCP-2176, SCP-244 translation;
Updated loading hints translation;
Added video settings description translation;
Added new subtitles item translation;
Added SCP-330 translation;
Added workstation translation;
Updated keybinds translation.

# **Checklist:**
- [x] I have tested the translation changes ingame
- [x] I have made sure to not commit changes to multiple translations at the same time, or non-translation repo files
- [x] I have ran `EncodingNormalizer.exe` on my changed files before commiting 
   -  *( Exception to this is when edits has __only__ been made in-browser. If this is the case, also* ***check this box*** *)*
- [x] I have made sure that I'm **not** submitting a duplicate translation 
- [x] I have made sure my addition follows guidelines described in the [CONTRIBUTING.md](https://github.com/northwood-studios/SCPSL-Translations/blob/master/.github/CONTRIBUTING.md) file
- [x] I have made sure to label my translation folder by [Microsoft Language Tag Standards](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-lcid/a9eac961-e77d-41a6-90a5-ce1a8b0cdb9c)
   - Only in cases of **new** translations (Can be tested [Here](https://rextester.com/WDXPS97501)). Also check this box if the change is **not** a new translation
> For more information regarding game translations, please visit our [README](https://github.com/northwood-studios/SCPSL-Translations/blob/master/README.md) page.

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/LoadingHints.txt
> +Бутылка SCP-207 не только увеличивает вашу скорость, но и частично восстанавливает ваше здоровье.
Бутылка SCP-207 не только увеличивает вашу скорость, но и частично восстанавливает здоровье.

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/LoadingHints.txt
> +Пока SCP-268 делает вас невидимым для людей, SCP-079 и SCP-939s все еще могут вас заметить.
SCP-939

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/LoadingHints.txt
> +SCP-018 крайте непредсказуем. Когда он брошен, ищите укрытие.
крайне

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/LoadingHints.txt
> +Тесла-ворота, на которые смотрит SCP-049, всегда будут активны.
SCP-079

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/LoadingHints.txt
> +SCP-106 может проходить через двери и стеклянные окна.
SCP-106 может проходить через двери и окна.

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/Class_Bio.txt
> +Участник секретной организации, основной целью которой является срыв операций Фонда и использование SCP в своих интересах. Им было поручено уничтожить <color=#FFFF7CFF>Научных Сотрудников</color> и <
Персонал Класса D

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/Class_Descriptions.txt
> +Помогите <color=#FF8E00>Сотрудникам Класса-Д</color> сбежать.\nНейтрализуйте всех остальных.
Персоналу Класса D

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/Class_Bio.txt
> +SCP-939-89 слеп. Он может видеть только с помощью звуковых волн. Из-за своей большой скорости передвижения и тихих шагов ему не составляет труда устроить засаду и убить людей, пользуясь их неаккуратн
SCP-939-89 слеп. Он может видеть только с помощью звуковых волн. Из-за своей большой скорости передвижения и тихих шагов, ему не составляет труда устроить засаду и убить людей, пользуясь их неаккуратностью.

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/AttachmentEditors.txt
> +ПОКАЗАТЬ СВОДВУ
СВОДКУ

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/LoadingHints.txt
> +Сбежавшие сотрудники класса-Д присоединяются к Повстанцам Хаоса, а сбежавшие учёные присоединяются к МОГ.
Сбежавший Персонал Класса D присоединяется к Повстанцам Хаоса, а сбежавшие Научные Сотрудники присоединяются к МОГ.

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/LoadingHints.txt
> +Учёные и класс-Д должны достигнуть поверхности, чтобы спастись.
Персонал Класса D и Научные Сотрудники

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/AttachmentEditors.txt
> +ПРЕДУСТАНОВКА
ПРЕДУСТАНОВКИ

2022-01-23 12:26 UTC, Liassid commented on Translations/ru/AttachmentEditors.txt
> +Пользовательский
Пользовательская

2022-03-24 18:20 UTC, GuyFawkes76 requested changes
I'm open for a discussion regarding the changes, which I'm unsure of.
And missing new lines need to be added as well.

2022-03-24 18:20 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Восстановление условий содержания SCP-106 можно произвести быстро, используя ломатель бедренной кости, находящийся в его камере содержания.
"используя установку для ломания бедренной кости, находящуюся в его камере содержания"?

2022-03-24 18:20 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +SCP-096 наиболее слаб, когда начал успокаиваться.
"когда только начинает"???

2022-03-24 18:20 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +SCP-939 вызывает амнезию у людей, затемняет их зрение, кусая их.
"у укушенных им людей, затемняет их зрение."?

2022-03-24 18:20 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +SCP-939 бесшумен при ходьбе, что делает его идеальным хищником из засады.
"засадным хищником"?

2022-03-24 18:20 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Шаги SCP отличаются от человеческих. Прислушайся!
"Слушай внимательно!"?

2022-03-24 18:20 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +SCP-049 при касании может мгновенного убить человека.
SCP-049 мгновенно убивает человека при касании.

2022-03-24 18:20 UTC, GuyFawkes76 commented on Translations/ru/SCP330.txt
> +Даёт большое количество небольших бонусов, включая регенерацию здоровья, бодрость, и AHP.
AHP так и переведены?

2022-03-24 18:20 UTC, GuyFawkes76 commented on Translations/ru/Subtitles.txt
> +Отряд Мобильной Опергруппы Epsilon-11, обозначенный как [designation], прибыл в комплекс.<split>Всему персоналу рекомендуется действовать по стандартным протоколам эвакуации, пока отряд МОГ не прибуд
"действовать согласно стандартным протоколам"

2022-03-25 08:57 UTC, bladuk commented on Translations/ru/SCP330.txt
> +Даёт большое количество небольших бонусов, включая регенерацию здоровья, бодрость, и AHP.
> AHP так и переведены?

В игре AHP так и отображается (https://i.imgur.com/2MQqA61.png)
"искусственное здоровье"?

2022-03-25 13:42 UTC, bladuk commented on Translations/ru/Class_Descriptions.txt
> +Помогите <color=#FF8E00>Сотрудникам Класса D</color> сбежать.\nНейтрализуйте всех остальных.
> Я думаю, лучше дать информацию про ПХ более полно, как это сделано в английской версии.

Не понял о чем идет речь, в английской версии указано не больше, чем у меня.

2022-03-27 10:09 UTC, bladuk commented on Translations/ru/Class_Descriptions.txt
> +Помогите <color=#FF8E00>Сотрудникам Класса D</color> сбежать.\nНейтрализуйте всех остальных.
Еще раз пересмотрел оригинальный перевод. Возможно, вы путаете файл Class_Descriptions с файлом Class_Bio?

2022-04-07 11:34 UTC, REALMWTH commented on Translations/ru/LoadingHints.txt
> +Вы можете бросать предметы ("T" по умолчанию). Это можно использовать для открытия дверей ключ-картой на расстоянии или разбивать стекло.
Проверьте использование кавычек в тексте перевода in-game. Раньше была проблема с отображением кавычек, нужно было добавлять перед кавычками слэш.

2022-04-07 11:38 UTC, REALMWTH commented on Translations/ru/LoadingHints.txt
> +SCP-939 бесшумен при ходьбе, что делает его идеальным хищником из засады.
"бесшумен при ходьбе" -> "передвигается бесшумно"

2022-04-07 11:46 UTC, REALMWTH commented
AttachmentNames.txt
45-я строка
"Система одиночного выстрела~Стандартная система. Нажатие на курок приведёт к одиночному выстрелу."

2022-04-07 11:49 UTC, REALMWTH commented
AttachmentNames.txt
46-я строка
Система двойного выстрела~Модифицированный `спусковой` механизм, приводящий в действие оба шептала одним нажатием.

2022-04-07 11:56 UTC, REALMWTH commented
[AttachmentParameters.txt](https://github.com/northwood-studios/SCPSL-Translations/pull/967/files#diff-4847637c20e0097f42df5925488d4ba2b9889c5bb457011208e21c754fa085cb)
Предлагаю переводить `projectiles` как `пули`

Количество `пуль`

2022-04-07 16:34 UTC, REALMWTH commented
@GuyFawkes76 @Liassid @bladuk ☝️ 
Я тут ряд предложений внёс 🥲

2022-04-07 16:47 UTC, REALMWTH commented
Обновление Summary.txt
`Раунд завершён!
ПОБЕДА SCP
ПОБЕДА ФОНДА SCP
ПОБЕДА СОПРОТИВЛЕНИЯ
НИЧЬЯ
Сбежавшие объекты заполонили комплекс. Объявлено чрезвычайное реагирование.
Все угрозы безопасности ликвидированы. Безопасность Зоны-02 восстановлена.
Комплекс зачищен от присутствия Фонда SCP. Оперативники ожидают дальнейших указаний.
Зона-02 находится под частичным контролем, но не без потерь. Победитель не был определён.
[summary_d_escaped] Сотрудников Класса D сбежало
[summary_s_escaped] Научных Сотрудников выжило
[summary_warhead_kills] Убито из-за детонации Боеголовки "Альфа"
Боеголовка "Альфа" не была детонирована в течение раунда.
Выполнение миссии заняло: [summary_round_minutes] минут и [summary_round_seconds] секунд.
[summary_scp_terminated] Уничтожено Объектов SCP
Следующий раунд начнётся через: [summary_next_round_countdown] секунд.
Вы нанесли [summary_damages] урона. Убитых вами игроков: [summary_kills]`

2022-04-07 20:10 UTC, bladuk commented on Translations/ru/LoadingHints.txt
> +Вы можете бросать предметы ("T" по умолчанию). Это можно использовать для открытия дверей ключ-картой на расстоянии или разбивать стекло.
> Проверьте использование кавычек в тексте перевода in-game. Раньше была проблема с отображением кавычек, нужно было добавлять перед кавычками слэш.

@REALMWTH, кавычки работают исправно (https://i.imgur.com/Eadelv8.png).

2022-04-08 21:47 UTC, REALMWTH commented
@bladuk, исправь, пожалуйста, Summary.txt, 4-я строка
`<size=120>ПОБЕДА СОПРОТИВЛЕНИЯ</size>`
До
![20220408224445_1](https://user-images.githubusercontent.com/1342847/162536312-624fb6e8-b1bc-479f-866c-daf93f370fc2.jpg)
 После
![изображение](https://user-images.githubusercontent.com/1342847/162536385-9186580f-d214-4798-854c-efad4a139ce7.png)

2022-04-10 22:33 UTC, GuyFawkes76 commented on Translations/ru/Class_Descriptions.txt
> +Помогите <color=#FF8E00>Сотрудникам Класса D</color> сбежать.\nНейтрализуйте всех остальных.
Да, посмотрел не в тот файл. Тут всё хорошо.

2022-04-10 23:18 UTC, GuyFawkes76 requested changes

2022-04-10 23:18 UTC, GuyFawkes76 commented on Translations/ru/Summary.txt
> +Сбежавшие объекты заполонили комплекс. Объявлено чрезвычайное реагирование.
"Emergency response has been scrambled." считаю, что нужно перевести как "Вызвана группа реагирования."
http://scp-ru.wikidot.com/security-clearance-levels#toc18
Задал по этому поводу вопрос знающим людям. Если неправильно понял, то поправим.

2022-04-11 15:06 UTC, GuyFawkes76 commented on Translations/ru/Summary.txt
> +Сбежавшие объекты заполонили комплекс. Объявлено чрезвычайное реагирование.
Понял правильно. Предложение значит, что вызвали группу реагирования.

2022-04-12 17:25 UTC, GuyFawkes76 approved these changes

2022-04-13 08:46 UTC, Blueberryy approved these changes
Круто сделано, но вот ещё несколько предложений:

2022-04-13 09:32 UTC, Blueberryy requested changes

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/Facility.txt
> +Переключить ADS
```suggestion
Переключить прицеливание
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +Научные Сотрудники и Персонал Класса D должны выбраться на поверхность чтобы спастись.
```suggestion
Научные Сотрудники и Персонал Класса D должны выбраться на поверхность, чтобы спастись.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +Детонация боеголовки Альфа может быть отменена из ее комнаты в зоне тяжёлого содержания.
```suggestion
Детонация боеголовки Альфа может быть отменена из её комнаты в зоне тяжёлого содержания.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +Максимизируйте своё преимущество, меняя обвесы для оружия под ситуацию, в которой вы оказались.
```suggestion
Максимизируйте своё преимущество, меняя модули для оружия под ситуацию, в которой вы оказались.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +Чем больше обвесов на оружии, тем оно тяжелее. Это влияет на вашу выносливость и скорость передвижения.
```suggestion
Чем больше модулей на оружии, тем оно тяжелее. Это влияет на вашу выносливость и скорость передвижения.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +Глушители не только приглушают выстрелы, но и скрывают вспышки.
```suggestion
Глушители не только приглушают выстрелы, но и гасят огонь при выстреле.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +Длинное и тяжёлое оружие менее точное при стрельбе на бегу.
```suggestion
Длинное и тяжёлое оружие менее точное при стрельбе от бедра.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +Ношение бронежилета увеличивает количество предметов и боеприпасов, которые вы можете нести.
```suggestion
Ношение бронежилета увеличивает количество предметов и боеприпасов, которые вы можете перетащить с собой.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +Удерживайте кнопку перезарядки, чтобы разрядить оружие и взять его патроны в инвентарь.
```suggestion
Удерживайте кнопку перезарядки, чтобы разрядить оружие и получить его боеприпасы в инвентарь.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +Оружие Повстанцев Хаоса мощное, но его припасы не появляются в комплексе. Используйте их с умом.
```suggestion
Оружие Повстанцев Хаоса мощное, но его боеприпасы невозможно найти в комплексе. Используйте их с умом.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +Граната может быть брошена с меньшей силой, если бросить ее, используя правую кнопку мыши.
```suggestion
Граната может быть брошена с меньшей силой, если бросить её, используя правую кнопку мыши.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +SCP-173 может свободно передвигаться в тёмных комнатах, даже если на него смотрят. Принеси фонарик!
```suggestion
SCP-173 может свободно передвигаться в тёмных комнатах, даже если на него смотрят. Найдите фонарик!
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +SCP-096 может бросаться вперёд во время ярости, ломая двери и убивая цели.
```suggestion
SCP-096 может бросаться вперёд во время ярости, ломая двери и убивая свои цели.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/LoadingHints.txt
> +SCP-939 вызывает амнезию у укушенных им людей, затемняет им зрение.
```suggestion
SCP-939 вызывает амнезию у укушенных им людей и ослепляет их.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/Summary.txt
>  Выполнение миссии заняло: [summary_round_minutes] минут и [summary_round_seconds] секунд.
```suggestion
Выполнение миссии заняло: [summary_round_minutes] мин. и [summary_round_seconds] сек.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/Summary.txt
>  Следующий раунд начнётся через: [summary_next_round_countdown] секунд.
```suggestion
Следующий раунд начнётся через: [summary_next_round_countdown] сек.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/SCP330.txt
> +Твердая карамель, наполненная всевозможными вкусами.
```suggestion
Твёрдая карамель, наполненная всевозможными вкусами.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/SCP330.txt
> +Даёт длительную регенерацию здоровья и временный иммунитет к большинству статусных эффектов.
```suggestion
Даёт длительную регенерацию здоровья и временный иммунитет к большинству негативных эффектов.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/Subtitles.txt
> +Опасность, процесс обеззараживания Зоны Лёгкого содержания начнётся через [time] минут.
```suggestion
Опасность, процесс обеззараживания Зоны Лёгкого содержания начнётся через [time] мин.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/Subtitles.txt
> +АКТИВИРОВАН ПРОЦЕСС АВАРИЙНОЙ ДЕТОНАЦИИ БОЕГОЛОВКИ АЛЬФА.<split>ПОДЗЕМНАЯ ЧАСТЬ КОМПЛЕКСА БУДЕТ УНИЧТОЖЕНА ЧЕРЕЗ [time] СЕКУНД.
```suggestion
АКТИВИРОВАН ПРОЦЕСС АВАРИЙНОЙ ДЕТОНАЦИИ БОЕГОЛОВКИ АЛЬФА.<split>ПОДЗЕМНАЯ ЧАСТЬ КОМПЛЕКСА БУДЕТ УНИЧТОЖЕНА ЧЕРЕЗ [time] СЕК.
```

2022-04-13 09:32 UTC, Blueberryy commented on Translations/ru/Subtitles.txt
> +ПРОЦЕСС ДЕТОНАЦИИ ВОЗОБНОВЛЁН, ДО ВЗРЫВА [time] СЕКУНД.
```suggestion
ПРОЦЕСС ДЕТОНАЦИИ ВОЗОБНОВЛЁН, ДО ВЗРЫВА [time] СЕК.
```

2022-04-13 11:31 UTC, Liassid commented
@bladuk Было бы хорошо поменять местами Мародёра и Репрессора в [Class_Names](https://github.com/northwood-studios/SCPSL-Translations/blob/master/Translations/ru/Class_Names.txt)

2022-04-13 12:04 UTC, GuyFawkes76 commented
@Liassid @bladuk Согласен, ещё можно не просто поменять местами, но ещё и заменить Репрессора на Усмирителя или Угнетателя (навряд ли на Тирана). Скорее на Угнетателя. Но тут не уверен.

2022-04-13 12:13 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Длинное и тяжёлое оружие менее точное при стрельбе на бегу.
Не согласен, потому что стрельба от бедра может быть и стоя на месте. В оригинале речь именно о стрельбе на бегу.

2022-04-13 12:14 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Ношение бронежилета увеличивает количество предметов и боеприпасов, которые вы можете нести.
Странно звучит. Лучше оставить, как было.

2022-04-13 12:33 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Глушители не только приглушают выстрелы, но и скрывают вспышки.
Масло масленное. Считаю, что было лучше.

2022-04-13 12:36 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Удерживайте кнопку перезарядки, чтобы разрядить оружие и взять его патроны в инвентарь.
```suggestion
Удерживайте кнопку перезарядки, чтобы разрядить оружие и добавить его боеприпасы в инвентарь.
```
Считаю, что лучше так.

2022-04-13 12:41 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +SCP-173 может свободно передвигаться в тёмных комнатах, даже если на него смотрят. Принеси фонарик!
```suggestion
SCP-173 может свободно передвигаться в тёмных комнатах, даже если на него смотрят. Носите с собой фонарик!
```

2022-04-13 12:41 UTC, bladuk commented on Translations/ru/AttachmentEditors.txt
> +ОЧИСТИТЬ ОБВЕСЫ
"Модули" в данном контексте звучит странно, мне кажется, лучше оставить "Обвесы".

2022-04-13 12:41 UTC, bladuk commented on Translations/ru/AttachmentEditors.txt
> +<size=52><color=#ccc>ТОЧКА МОДИФИКАЦИИ ОРУЖИЯ SITE-02</color> - ГОТОВА</size>\n<size=42><color=#ccc>ПОЖАЛУЙСТА, ВОЗЬМИТЕ ВАШЕ ОРУЖИЕ В РУКИ ДЛЯ МОДИФИКАЦИИ ЕГО ОБВЕСОВ.</color></size>
"Модули" в данном контексте звучит странно, мне кажется, лучше оставить "Обвесы".

2022-04-13 12:42 UTC, bladuk commented on Translations/ru/Subtitles.txt
> +Опасность, процесс обеззараживания Зоны Лёгкого содержания начнётся через [time] минут.
Не считаю уместным здесь использование сокращений. В оригинальном переводе сокращения также не используются

2022-04-13 12:43 UTC, bladuk commented on Translations/ru/Subtitles.txt
> +АКТИВИРОВАН ПРОЦЕСС АВАРИЙНОЙ ДЕТОНАЦИИ БОЕГОЛОВКИ АЛЬФА.<split>ПОДЗЕМНАЯ ЧАСТЬ КОМПЛЕКСА БУДЕТ УНИЧТОЖЕНА ЧЕРЕЗ [time] СЕКУНД.
Не считаю уместным здесь использование сокращений. В оригинальном переводе сокращения также не используются.

2022-04-13 12:43 UTC, bladuk commented on Translations/ru/Subtitles.txt
> +ПРОЦЕСС ДЕТОНАЦИИ ВОЗОБНОВЛЁН, ДО ВЗРЫВА [time] СЕКУНД.
Не считаю уместным здесь использование сокращений. В оригинальном переводе сокращения также не используются.

2022-04-13 12:45 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +SCP-939 вызывает амнезию у укушенных им людей, затемняет им зрение.
В оригинале смысл в том, что геймплейно амнезия выражается в затемнении зрения.

2022-04-13 12:46 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +SCP-096 может бросаться вперёд во время ярости, ломая двери и убивая цели.
Не считаю нужным добавление здесь слова "свои".

2022-04-13 12:47 UTC, GuyFawkes76 commented on Translations/ru/LoadingHints.txt
> +Максимизируйте своё преимущество, меняя обвесы для оружия под ситуацию, в которой вы оказались.
Вопрос дискуссионный, "обвесы", "моды", "модули" околоравнозначные понятия, как по мне.

2022-04-13 12:48 UTC, GuyFawkes76 commented on Translations/ru/SCP330.txt
> +Даёт длительную регенерацию здоровья и временный иммунитет к большинству статусных эффектов.
Не считаю, что данное сужение относящихся к вопросу эффектов будет здесь уместно.

2022-04-13 12:49 UTC, GuyFawkes76 approved these changes

2022-04-13 13:03 UTC, merged